#ifndef __CFIDOSUITOKEN_H
#define __CFIDOSUITOKEN_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

// This class provides the secure display token generated by the FIDO SUI application

// on behalf of other biometric authenticators.

// It implements the `ISource` interface.

//

#define CFidoSuiToken_UID UINT32_C(1026)

#endif /* __CFIDOSUITOKEN_H */
