#ifndef __IUNWRAPKEYS_INVOKE_H
#define __IUNWRAPKEYS_INVOKE_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#include "IUnwrapKeys.h"

#define IUnwrapKeys_DEFINE_INVOKE(func, prefix, type) \
  int32_t func(ObjectCxt h, ObjectOp op, ObjectArg *a, ObjectCounts k) \
  { \
    type me = (type) h; \
    switch (ObjectOp_methodID(op)) { \
      case Object_OP_release: { \
        return prefix##release(me); \
      } \
      case Object_OP_retain: { \
        return prefix##retain(me); \
      } \
      case IUnwrapKeys_OP_unwrap: { \
        if (k != ObjectCounts_pack(1, 1, 0, 0)) { \
          break; \
        } \
        const void *wrapped_ptr = (const void*) a[0].b.ptr; \
        size_t wrapped_len = a[0].b.size / 1; \
        void *unwrapped_ptr = (void*) a[1].b.ptr; \
        size_t unwrapped_len = a[1].b.size / 1; \
        int32_t r = prefix##unwrap(me, wrapped_ptr, wrapped_len, unwrapped_ptr, unwrapped_len, &unwrapped_len); \
        a[1].b.size = unwrapped_len * 1; \
        return r; \
      } \
    } \
    return Object_ERROR_INVALID; \
  }

#endif /* __IUNWRAPKEYS_INVOKE_H */