// Copyright (c) 2016 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

// Test interface


interface TestParams {

   method setall(in buffer bi01,
                 in buffer bi02,
                 in buffer bi03,
                 in buffer bi04,
                 in buffer bi05,
                 in buffer bi06,
                 in buffer bi07,
                 in buffer bi08,
                 in buffer bi09,
                 in buffer bi10,
                 in buffer bi11,
                 in buffer bi12,
                 in buffer bi13,
                 in buffer bi14,
                 in buffer bi15,
                 in interface oi01,
                 in interface oi02,
                 in interface oi03,
                 in interface oi04,
                 in interface oi05,
                 in interface oi06,
                 in interface oi07,
                 in interface oi08,
                 in interface oi09,
                 in interface oi10,
                 in interface oi11,
                 in interface oi12,
                 in interface oi13,
                 in interface oi14,
                 in interface oi15,
                 out buffer bo01,
                 out buffer bo02,
                 out buffer bo03,
                 out buffer bo04,
                 out buffer bo05,
                 out buffer bo06,
                 out buffer bo07,
                 out buffer bo08,
                 out buffer bo09,
                 out buffer bo10,
                 out buffer bo11,
                 out buffer bo12,
                 out buffer bo13,
                 out buffer bo14,
                 out buffer bo15,
                 out interface oo01,
                 out interface oo02,
                 out interface oo03,
                 out interface oo04,
                 out interface oo05,
                 out interface oo06,
                 out interface oo07,
                 out interface oo08,
                 out interface oo09,
                 out interface oo10,
                 out interface oo11,
                 out interface oo12,
                 out interface oo13,
                 out interface oo14,
                 out interface oo15);
};
