#ifndef __CHDCP2P2SERVICE_H
#define __CHDCP2P2SERVICE_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2016 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CHdcp2p2Service_UID UINT32_C(67)

#endif /* __CHDCP2P2SERVICE_H */
