#ifndef __CHDCP2PROVISION_H
#define __CHDCP2PROVISION_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2016 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CHdcp2Provision_UID UINT32_C(86)

#endif /* __CHDCP2PROVISION_H */
