#ifndef __COBSERVER_H
#define __COBSERVER_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2016 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CObserver_UID UINT32_C(0xFFFF0005)

#endif /* __COBSERVER_H */
