#ifndef __CTEST1_H
#define __CTEST1_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2016 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CTest1_UID UINT32_C(0xFFFF0004)

#endif /* __CTEST1_H */
