#ifndef __CTESTPARAMS_H
#define __CTESTPARAMS_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2016 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CTestParams_UID UINT32_C(0xFFFF0003)

#endif /* __CTESTPARAMS_H */
