#ifndef __INOOP_H
#define __INOOP_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define NoOp_OP_noop 0

static inline int32_t
NoOp_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
NoOp_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
NoOp_noop(Object self)
{
  return Object_invoke(self, NoOp_OP_noop, 0, 0);
}


#endif /* __INOOP_H */
