#ifndef __INOOP_INVOKE_H
#define __INOOP_INVOKE_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#include "INoOp.h"

#define NoOp_DEFINE_INVOKE(func, prefix, type) \
  int32_t func(ObjectCxt h, ObjectOp op, ObjectArg *a, ObjectCounts k) \
  { \
    type me = (type) h; \
    switch (ObjectOp_methodID(op)) { \
      case Object_OP_release: { \
        return prefix##release(me); \
      } \
      case Object_OP_retain: { \
        return prefix##retain(me); \
      } \
      case NoOp_OP_noop: { \
        return prefix##noop(me); \
      } \
    } \
    return Object_ERROR_INVALID; \
  }

#endif /* __INOOP_INVOKE_H */
