#ifndef __IOBSERVER_INVOKE_H
#define __IOBSERVER_INVOKE_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#include "IObserver.h"

#define IObserver_DEFINE_INVOKE(func, prefix, type) \
  int32_t func(ObjectCxt h, ObjectOp op, ObjectArg *a, ObjectCounts k) \
  { \
    type me = (type) h; \
    switch (ObjectOp_methodID(op)) { \
      case Object_OP_release: { \
        return prefix##release(me); \
      } \
      case Object_OP_retain: { \
        return prefix##retain(me); \
      } \
      case IObserver_OP_observe: { \
        if (k != ObjectCounts_pack(1, 0, 1, 0) || \
          a[0].b.size != 4) { \
          break; \
        } \
        const uint32_t *contextSize_ptr = (const uint32_t*) a[0].b.ptr; \
        return prefix##observe(me, a[1].o, *contextSize_ptr); \
      } \
      case IObserver_OP_dump: { \
        if (k != ObjectCounts_pack(0, 1, 0, 0)) { \
          break; \
        } \
        void *context_ptr = (void*) a[0].b.ptr; \
        size_t context_len = a[0].b.size / 1; \
        int32_t r = prefix##dump(me, context_ptr, context_len, &context_len); \
        a[0].b.size = context_len * 1; \
        return r; \
      } \
    } \
    return Object_ERROR_INVALID; \
  }

#endif /* __IOBSERVER_INVOKE_H */
