#ifndef __ITESTGETSET_H
#define __ITESTGETSET_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2016 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

// Test interface

#define TestGetSet_OP_get 0
#define TestGetSet_OP_set 1

static inline int32_t
TestGetSet_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
TestGetSet_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
TestGetSet_get(Object self, void *bo_ptr, size_t bo_len, size_t *bo_lenout, Object *oo_ptr)
{
  ObjectArg a[2];
  a[0].b = (ObjectBuf) { bo_ptr, bo_len * 1 };

  int32_t result = Object_invoke(self, TestGetSet_OP_get, a, ObjectCounts_pack(0, 1, 0, 1));

  *bo_lenout = a[0].b.size / 1;
  *oo_ptr = a[1].o;

  return result;
}

static inline int32_t
TestGetSet_set(Object self, const void *bi_ptr, size_t bi_len, Object oi_val)
{
  ObjectArg a[2];
  a[0].bi = (ObjectBufIn) { bi_ptr, bi_len * 1 };
  a[1].o = oi_val;

  return Object_invoke(self, TestGetSet_OP_set, a, ObjectCounts_pack(1, 0, 1, 0));
}


#endif /* __ITESTGETSET_H */
