#ifndef __COEMUNWRAPKEYS_H
#define __COEMUNWRAPKEYS_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

/**
 * This class can be implemented by an OEM to enable Qualcomm's Generic DRM
 * Key Provisioning Solution.  This class implements `IUnwrapKeys`.
 */

#define COEMUnwrapKeys_UID UINT32_C(60)

#endif /* __COEMUNWRAPKEYS_H */