#ifndef __CTESTSANDBOX_H
#define __CTESTSANDBOX_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CTestSandbox_UID UINT32_C(0xffff0001)

#endif /* __CTESTSANDBOX_H */
