#ifndef __CHDCP1PROVISION_H
#define __CHDCP1PROVISION_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2016 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CHdcp1Provision_UID UINT32_C(85)

#endif /* __CHDCP1PROVISION_H */
