
/**
* Name:        ureg_sw_lpass_hw_af_core.h
* Date:        Oct 17 2012
* Author:      automatically created using QSDS_UregGen
*              from LPASS_HW_AF_Core.FLAT
* Description: MicroReg global SW header file
**/


#ifndef U_REG_SW_LPASS_HW_AF_CORE_H
#define U_REG_SW_LPASS_HW_AF_CORE_H

/**
 * Register name->address conversion
 */

#define LPASS_HW_AF_BASE  (0x17160000)

/**
 * For slave lpass_hw_af_core:
 */

// -- For HW_AF_VERSION
#define A_HW_AF_VERSION (0x0)
#define HW_AF_VERSION___RWC "R"
#define HW_AF_VERSION___POR 0x10000001
#define HW_AF_VERSION___S 0
#define HW_AF_VERSION___M 0xFFFFFFFF


#define HW_AF_VERSION__MAJOR___S 28
#define HW_AF_VERSION__MAJOR___M 0xF0000000

#define HW_AF_VERSION__MINOR___S 16
#define HW_AF_VERSION__MINOR___M 0xFFF0000

#define HW_AF_VERSION__STEP___S 0
#define HW_AF_VERSION__STEP___M 0xFFFF


// -- For HW_AF_CTRL
#define A_HW_AF_CTRL (0x1C)
#define HW_AF_CTRL___RWC "RW"
#define HW_AF_CTRL___POR 0
#define HW_AF_CTRL___S 0
#define HW_AF_CTRL___M 0x7


#define HW_AF_CTRL__GO_BUF2___S 2
#define HW_AF_CTRL__GO_BUF2___M 0x4

#define HW_AF_CTRL__STOP___S 1
#define HW_AF_CTRL__STOP___M 0x2

#define HW_AF_CTRL__GO___S 0
#define HW_AF_CTRL__GO___M 0x1


// -- For HW_AF_BUF_TYPE
#define A_HW_AF_BUF_TYPE (0x20)
#define HW_AF_BUF_TYPE___RWC "RW"
#define HW_AF_BUF_TYPE___POR 0
#define HW_AF_BUF_TYPE___S 0
#define HW_AF_BUF_TYPE___M 0xFFFFFFFF


#define HW_AF_BUF_TYPE__ADDR___S 0
#define HW_AF_BUF_TYPE__ADDR___M 0xFFFFFFFF


// -- For HW_AF_CFG_TYPE
#define A_HW_AF_CFG_TYPE (0x24)
#define HW_AF_CFG_TYPE___RWC "RW"
#define HW_AF_CFG_TYPE___POR 0
#define HW_AF_CFG_TYPE___S 0
#define HW_AF_CFG_TYPE___M 0xFFFFFFFF


#define HW_AF_CFG_TYPE__ADDR___S 0
#define HW_AF_CFG_TYPE__ADDR___M 0xFFFFFFFF


// -- For HW_AF_FILTER_OUT
#define A_HW_AF_FILTER_OUT (0x28)
#define HW_AF_FILTER_OUT___RWC "RW"
#define HW_AF_FILTER_OUT___POR 0
#define HW_AF_FILTER_OUT___S 0
#define HW_AF_FILTER_OUT___M 0xFFFFFFFF


#define HW_AF_FILTER_OUT__ADDR___S 0
#define HW_AF_FILTER_OUT__ADDR___M 0xFFFFFFFF


// -- For HW_AF_BUF_TYPE_BUF2
#define A_HW_AF_BUF_TYPE_BUF2 (0x2C)
#define HW_AF_BUF_TYPE_BUF2___RWC "RW"
#define HW_AF_BUF_TYPE_BUF2___POR 0
#define HW_AF_BUF_TYPE_BUF2___S 0
#define HW_AF_BUF_TYPE_BUF2___M 0xFFFFFFFF


#define HW_AF_BUF_TYPE_BUF2__ADDR___S 0
#define HW_AF_BUF_TYPE_BUF2__ADDR___M 0xFFFFFFFF


// -- For HW_AF_CFG_TYPE_BUF2
#define A_HW_AF_CFG_TYPE_BUF2 (0x30)
#define HW_AF_CFG_TYPE_BUF2___RWC "RW"
#define HW_AF_CFG_TYPE_BUF2___POR 0
#define HW_AF_CFG_TYPE_BUF2___S 0
#define HW_AF_CFG_TYPE_BUF2___M 0xFFFFFFFF


#define HW_AF_CFG_TYPE_BUF2__ADDR___S 0
#define HW_AF_CFG_TYPE_BUF2__ADDR___M 0xFFFFFFFF


// -- For HW_AF_FILTER_OUT_BUF2
#define A_HW_AF_FILTER_OUT_BUF2 (0x34)
#define HW_AF_FILTER_OUT_BUF2___RWC "RW"
#define HW_AF_FILTER_OUT_BUF2___POR 0
#define HW_AF_FILTER_OUT_BUF2___S 0
#define HW_AF_FILTER_OUT_BUF2___M 0xFFFFFFFF


#define HW_AF_FILTER_OUT_BUF2__ADDR___S 0
#define HW_AF_FILTER_OUT_BUF2__ADDR___M 0xFFFFFFFF


// -- For HW_AF_DEBUG
#define A_HW_AF_DEBUG (0x38)
#define HW_AF_DEBUG___RWC "RW"
#define HW_AF_DEBUG___POR 0
#define HW_AF_DEBUG___S 0
#define HW_AF_DEBUG___M 0x1


#define HW_AF_DEBUG__DMA_LOOPBACK___S 0
#define HW_AF_DEBUG__DMA_LOOPBACK___M 0x1


// -- For HW_AF_SPARE
#define A_HW_AF_SPARE (0xFC)
#define HW_AF_SPARE___RWC "RW"
#define HW_AF_SPARE___POR 0
#define HW_AF_SPARE___S 0
#define HW_AF_SPARE___M 0xFFFFFFFF


#define HW_AF_SPARE__SPARE___S 0
#define HW_AF_SPARE__SPARE___M 0xFFFFFFFF


// -- For HW_AF_INTERRUPT_EN
#define A_HW_AF_INTERRUPT_EN (0x1004)
#define HW_AF_INTERRUPT_EN___RWC "RW"
#define HW_AF_INTERRUPT_EN___POR 0
#define HW_AF_INTERRUPT_EN___S 0
#define HW_AF_INTERRUPT_EN___M 0x3


#define HW_AF_INTERRUPT_EN__LOOPBACK_DONE___S 1
#define HW_AF_INTERRUPT_EN__LOOPBACK_DONE___M 0x2

#define HW_AF_INTERRUPT_EN__FILTER_DONE___S 0
#define HW_AF_INTERRUPT_EN__FILTER_DONE___M 0x1


// -- For HW_AF_INTERRUPT_STATUS
#define A_HW_AF_INTERRUPT_STATUS (0x1008)
#define HW_AF_INTERRUPT_STATUS___RWC "R"
#define HW_AF_INTERRUPT_STATUS___POR 0
#define HW_AF_INTERRUPT_STATUS___S 0
#define HW_AF_INTERRUPT_STATUS___M 0x3


#define HW_AF_INTERRUPT_STATUS__LOOPBACK_DONE_STA___S 1
#define HW_AF_INTERRUPT_STATUS__LOOPBACK_DONE_STA___M 0x2
#define HW_AF_INTERRUPT_STATUS__LOOPBACK_DONE_STA__NO_EVENT 0x0
#define HW_AF_INTERRUPT_STATUS__LOOPBACK_DONE_STA__AUDIO_BLOCK_IS_TRANSMITTED 0x1

#define HW_AF_INTERRUPT_STATUS__FILTER_DONE_STA___S 0
#define HW_AF_INTERRUPT_STATUS__FILTER_DONE_STA___M 0x1
#define HW_AF_INTERRUPT_STATUS__FILTER_DONE_STA__NO_EVENT 0x0
#define HW_AF_INTERRUPT_STATUS__FILTER_DONE_STA__AUDIO_BLOCK_IS_TRANSMITTED 0x1


// -- For HW_AF_INTERRUPT_CLR
#define A_HW_AF_INTERRUPT_CLR (0x100C)
#define HW_AF_INTERRUPT_CLR___RWC "C"
#define HW_AF_INTERRUPT_CLR___POR 0
#define HW_AF_INTERRUPT_CLR___S 0
#define HW_AF_INTERRUPT_CLR___M 0x3


#define HW_AF_INTERRUPT_CLR__LOOPBACK_DONE_ACK___S 1
#define HW_AF_INTERRUPT_CLR__LOOPBACK_DONE_ACK___M 0x2
#define HW_AF_INTERRUPT_CLR__LOOPBACK_DONE_ACK__NO_EFFECT 0x0
#define HW_AF_INTERRUPT_CLR__LOOPBACK_DONE_ACK__CLEAR_STATUS 0x1

#define HW_AF_INTERRUPT_CLR__FILTER_DONE_ACK___S 0
#define HW_AF_INTERRUPT_CLR__FILTER_DONE_ACK___M 0x1
#define HW_AF_INTERRUPT_CLR__FILTER_DONE_ACK__NO_EFFECT 0x0
#define HW_AF_INTERRUPT_CLR__FILTER_DONE_ACK__CLEAR_STATUS 0x1


// -- For HW_AF_APP_INTERRUPT_EN
#define A_HW_AF_APP_INTERRUPT_EN (0x2004)
#define HW_AF_APP_INTERRUPT_EN___RWC "RW"
#define HW_AF_APP_INTERRUPT_EN___POR 0
#define HW_AF_APP_INTERRUPT_EN___S 0
#define HW_AF_APP_INTERRUPT_EN___M 0x3


#define HW_AF_APP_INTERRUPT_EN__LOOPBACK_DONE___S 1
#define HW_AF_APP_INTERRUPT_EN__LOOPBACK_DONE___M 0x2

#define HW_AF_APP_INTERRUPT_EN__FILTER_DONE___S 0
#define HW_AF_APP_INTERRUPT_EN__FILTER_DONE___M 0x1


// -- For HW_AF_APP_INTERRUPT_STATUS
#define A_HW_AF_APP_INTERRUPT_STATUS (0x2008)
#define HW_AF_APP_INTERRUPT_STATUS___RWC "R"
#define HW_AF_APP_INTERRUPT_STATUS___POR 0
#define HW_AF_APP_INTERRUPT_STATUS___S 0
#define HW_AF_APP_INTERRUPT_STATUS___M 0x3


#define HW_AF_APP_INTERRUPT_STATUS__LOOPBACK_DONE_STA___S 1
#define HW_AF_APP_INTERRUPT_STATUS__LOOPBACK_DONE_STA___M 0x2
#define HW_AF_APP_INTERRUPT_STATUS__LOOPBACK_DONE_STA__NO_EVENT 0x0
#define HW_AF_APP_INTERRUPT_STATUS__LOOPBACK_DONE_STA__AUDIO_BLOCK_IS_TRANSMITTED 0x1

#define HW_AF_APP_INTERRUPT_STATUS__FILTER_DONE_STA___S 0
#define HW_AF_APP_INTERRUPT_STATUS__FILTER_DONE_STA___M 0x1
#define HW_AF_APP_INTERRUPT_STATUS__FILTER_DONE_STA__NO_EVENT 0x0
#define HW_AF_APP_INTERRUPT_STATUS__FILTER_DONE_STA__AUDIO_BLOCK_IS_TRANSMITTED 0x1


// -- For HW_AF_APP_INTERRUPT_CLR
#define A_HW_AF_APP_INTERRUPT_CLR (0x200C)
#define HW_AF_APP_INTERRUPT_CLR___RWC "C"
#define HW_AF_APP_INTERRUPT_CLR___POR 0
#define HW_AF_APP_INTERRUPT_CLR___S 0
#define HW_AF_APP_INTERRUPT_CLR___M 0x3


#define HW_AF_APP_INTERRUPT_CLR__LOOPBACK_DONE_ACK___S 1
#define HW_AF_APP_INTERRUPT_CLR__LOOPBACK_DONE_ACK___M 0x2
#define HW_AF_APP_INTERRUPT_CLR__LOOPBACK_DONE_ACK__NO_EFFECT 0x0
#define HW_AF_APP_INTERRUPT_CLR__LOOPBACK_DONE_ACK__CLEAR_STATUS 0x1

#define HW_AF_APP_INTERRUPT_CLR__FILTER_DONE_ACK___S 0
#define HW_AF_APP_INTERRUPT_CLR__FILTER_DONE_ACK___M 0x1
#define HW_AF_APP_INTERRUPT_CLR__FILTER_DONE_ACK__NO_EFFECT 0x0
#define HW_AF_APP_INTERRUPT_CLR__FILTER_DONE_ACK__CLEAR_STATUS 0x1


#endif  // U_REG_SW_LPASS_HW_AF_CORE_H
