/*
* Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
* Qualcomm Technologies Proprietary and Confidential.
*/

#pragma once

#define LAYOUT_MASK_USE_SDAT  0x08000000
#define LAYOUT_MASK_USE_SDTT  0x04000000
#define LAYOUT_MASK_HAS_OK    0x02000000
#define LAYOUT_MASK_HAS_PNG   0x01000000

#define LAYOUT_MASK_OP      0x0000000F
#define LAYOUT_MASK_OP_REG  0x00000001
#define LAYOUT_MASK_OP_AUTH 0x00000002
#define LAYOUT_MASK_OP_SIGN 0x00000003

#define LAYOUT_MASK_TA      0x0000FFF0

typedef enum {
  /** Fingerprint */
  LAYOUT_ID_FP_REG      = ( 0x10 | LAYOUT_MASK_OP_REG  | LAYOUT_MASK_USE_SDAT),
  LAYOUT_ID_FP_AUTH     = ( 0x10 | LAYOUT_MASK_OP_AUTH | LAYOUT_MASK_USE_SDAT),
  LAYOUT_ID_FP_TX       = ( 0x10 | LAYOUT_MASK_OP_SIGN | LAYOUT_MASK_USE_SDTT),
  LAYOUT_ID_FP_TX_PNG   = ( 0x10 | LAYOUT_MASK_OP_SIGN | LAYOUT_MASK_USE_SDTT | LAYOUT_MASK_HAS_PNG),

  /** Iris */
  //LAYOUT_ID_IRIS_REG    = ( 0x20 | LAYOUT_MASK_OP_REG   | LAYOUT_MASK_HAS_OK),
  //LAYOUT_ID_IRIS_AUTH   = ( 0x20 | LAYOUT_MASK_OP_AUTH  | LAYOUT_MASK_HAS_OK),
  LAYOUT_ID_IRIS_TX     = ( 0x20 | LAYOUT_MASK_OP_SIGN  | LAYOUT_MASK_USE_SDTT | LAYOUT_MASK_HAS_OK),
  LAYOUT_ID_IRIS_TX_PNG = ( 0x20 | LAYOUT_MASK_OP_SIGN  | LAYOUT_MASK_USE_SDTT | LAYOUT_MASK_HAS_OK | LAYOUT_MASK_HAS_PNG),

  /** SampleAuth */
  LAYOUT_ID_SAMPLE_REG      = ( 0x100 | LAYOUT_MASK_OP_REG   | LAYOUT_MASK_USE_SDAT | LAYOUT_MASK_HAS_OK),
  LAYOUT_ID_SAMPLE_AUTH     = ( 0x100 | LAYOUT_MASK_OP_AUTH  | LAYOUT_MASK_USE_SDAT | LAYOUT_MASK_HAS_OK),
  LAYOUT_ID_SAMPLE_TX       = ( 0x100 | LAYOUT_MASK_OP_SIGN  | LAYOUT_MASK_USE_SDAT | LAYOUT_MASK_USE_SDTT | LAYOUT_MASK_HAS_OK),
  LAYOUT_ID_SAMPLE_TX_PNG   = ( 0x100 | LAYOUT_MASK_OP_SIGN  | LAYOUT_MASK_USE_SDAT | LAYOUT_MASK_USE_SDTT | LAYOUT_MASK_HAS_OK | LAYOUT_MASK_HAS_PNG),

  LAYOUT_ID_INVALID = 0x7FFFFFFF
} layout_id_t;


