#ifndef __CAPP_H
#define __CAPP_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CApp_UID UINT32_C(0)

#endif /* __CAPP_H */
