#ifndef __CAPPMESSAGE_H
#define __CAPPMESSAGE_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CAppMessage_UID UINT32_C(21)

#endif /* __CAPPMESSAGE_H */
