#ifndef __CCIPHER_H
#define __CCIPHER_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CCipherAES128_UID UINT32_C(35)

#define CCipherAES256_UID UINT32_C(36)

#define CCipherTripleDES_UID UINT32_C(37)

#endif /* __CCIPHER_H */
