#ifndef __CCRYPTO_H
#define __CCRYPTO_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

// This class implements the ICrypo interface.

#define CCrypto_UID UINT32_C(11)

#endif /* __CCRYPTO_H */