#ifndef __CDATACACHE_H
#define __CDATACACHE_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CDataCache_UID UINT32_C(19)

#endif /* __CDATACACHE_H */
