#ifndef __CDEBUGPOLICYSOURCE_H
#define __CDEBUGPOLICYSOURCE_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2019 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CDebugPolicySource_UID UINT32_C(64)

#endif /* __CDEBUGPOLICYSOURCE_H */
