#ifndef __CDEVICEID_H
#define __CDEVICEID_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CDeviceID_UID UINT32_C(12)

#endif /* __CDEVICEID_H */
