#ifndef __CESESERVICE_H
#define __CESESERVICE_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

// This class implements the IESEService interface.

#define CESEService_UID UINT32_C(255)

#endif /* __CESESERVICE_H */
