#ifndef __CGPAPP_H
#define __CGPAPP_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CGPApp_UID UINT32_C(33)

#endif /* __CGPAPP_H */
