#ifndef __CGPSERVICES_H
#define __CGPSERVICES_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

// This class provides a GP Services class for communication with TAs

//

#define CGPServices_UID UINT32_C(32)

#endif /* __CGPSERVICES_H */
