#ifndef __CGUESTVM_H
#define __CGUESTVM_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CGuestVM_UID UINT32_C(63)

#endif /* __CGUESTVM_H */
