#ifndef __CHASH_H
#define __CHASH_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CHashNone_UID UINT32_C(38)

#define CHashSHA1_UID UINT32_C(39)

#define CHashSHA256_UID UINT32_C(40)

#endif /* __CHASH_H */
