#ifndef __CHAVENTOKENAPP_H
#define __CHAVENTOKENAPP_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2016 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CHavenTokenApp_UID UINT32_C(78)

#endif /* __CHAVENTOKENAPP_H */
