#ifndef __CHDCPENCRYPTION_H
#define __CHDCPENCRYPTION_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2016 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CHdcpEncryption_UID UINT32_C(65)

#endif /* __CHDCPENCRYPTION_H */
