#ifndef __CHDMISTATUS_H
#define __CHDMISTATUS_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CHdmiStatus_UID UINT32_C(13)

#endif /* __CHDMISTATUS_H */
