#ifndef __CHMAC_H
#define __CHMAC_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CHmacSHA1_UID UINT32_C(41)

#define CHmacSHA256_UID UINT32_C(42)

#endif /* __CHMAC_H */
