#ifndef __CHWFUSE_H
#define __CHWFUSE_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CHwFuse_UID UINT32_C(28)

#endif /* __CHWFUSE_H */
