#ifndef __CI2C_H
#define __CI2C_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CI2C_UID UINT32_C(43)

#endif /* __CI2C_H */
