#ifndef __CINTMASK_H
#define __CINTMASK_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CIntMask_UID UINT32_C(53)

#endif /* __CINTMASK_H */
