#ifndef __CLISTENER_H
#define __CLISTENER_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CListener_UID UINT32_C(48)

#endif /* __CLISTENER_H */
