#ifndef __CMACCHIATO_H
#define __CMACCHIATO_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CMacchiato_UID UINT32_C(49)

#endif /* __CMACCHIATO_H */
