#ifndef __CNSMEM_H
#define __CNSMEM_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CNSMem_UID UINT32_C(15)

#endif /* __CNSMEM_H */
