#ifndef __CNSSYSTEMREG_H
#define __CNSSYSTEMREG_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CNSSystemReg_UID UINT32_C(96)

#endif /* __CNSSYSTEMREG_H */
