#ifndef __COEMBUF_H
#define __COEMBUF_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define COEMBuf_UID UINT32_C(52)

#endif /* __COEMBUF_H */
