#ifndef __CPRNGSOURCE_H
#define __CPRNGSOURCE_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

// This class provides a stream of pseudo-random data. It implements the

// `ISource` interface.

//

#define CPrngSource_UID UINT32_C(17)

#endif /* __CPRNGSOURCE_H */
