#ifndef __CPVC_H
#define __CPVC_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CPVC_UID UINT32_C(14)

#endif /* __CPVC_H */
