#ifndef __CRESETTIMER_H
#define __CRESETTIMER_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CResetTimer_UID UINT32_C(20)

#endif /* __CRESETTIMER_H */
