#ifndef __CSECUREDISPLAY_H
#define __CSECUREDISPLAY_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CSecureDisplay_UID UINT32_C(25)

#endif /* __CSECUREDISPLAY_H */
