#ifndef __CSECURECHANNEL_H
#define __CSECURECHANNEL_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CSecureChannel_UID UINT32_C(26)

#endif /* __CSECURECHANNEL_H */
