#ifndef __CSECURECAMERA_H
#define __CSECURECAMERA_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2016 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CSecureCamera_UID UINT32_C(56)

#endif /* __CSECURECAMERA_H */
