#ifndef __CSHAREDBUFFER_H
#define __CSHAREDBUFFER_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CSharedBuffer_UID UINT32_C(23)

#endif /* __CSHAREDBUFFER_H */
