#ifndef __CSPCOM_H
#define __CSPCOM_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2016 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CSPCOM_UID UINT32_C(55)

#endif /* __CSPCOM_H */
