#ifndef __CSPI_H
#define __CSPI_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CSPI_UID UINT32_C(16)

#endif /* __CSPI_H */
