#ifndef __CSYNC_H
#define __CSYNC_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CSync_UID UINT32_C(51)

#endif /* __CSYNC_H */
