#ifndef __CTLMM_H
#define __CTLMM_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CTLMM_UID UINT32_C(45)

#endif /* __CTLMM_H */
