#ifndef __CTRANSNSADDR_H
#define __CTRANSNSADDR_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CTransNSAddr_UID UINT32_C(54)

#endif /* __CTRANSNSADDR_H */
