#ifndef __CUPTIME_H
#define __CUPTIME_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define CUptime_UID UINT32_C(18)

#endif /* __CUPTIME_H */
