#ifndef __IENV_INVOKE_H
#define __IENV_INVOKE_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"
#include "IOpener.h"

#include "IEnv.h"

#define IEnv_DEFINE_INVOKE(func, prefix, type) \
  int32_t func(ObjectCxt h, ObjectOp op, ObjectArg *a, ObjectCounts k) \
  { \
    type me = (type) h; \
    switch (ObjectOp_methodID(op)) { \
      case Object_OP_release: { \
        return prefix##release(me); \
      } \
      case Object_OP_retain: { \
        return prefix##retain(me); \
      } \
      case IOpener_OP_open: { \
        if (k != ObjectCounts_pack(1, 0, 0, 1) || \
          a[0].b.size != 4) { \
          break; \
        } \
        const uint32_t *id_ptr = (const uint32_t*) a[0].b.ptr; \
        return prefix##open(me, *id_ptr, &a[1].o); \
      } \
      case IEnv_OP_log: { \
        if (k != ObjectCounts_pack(1, 0, 0, 0)) { \
          break; \
        } \
        const void *text_ptr = (const void*) a[0].b.ptr; \
        size_t text_len = a[0].b.size / 1; \
        return prefix##log(me, text_ptr, text_len); \
      } \
      case IEnv_OP_exit: { \
        if (k != ObjectCounts_pack(1, 0, 0, 0) || \
          a[0].b.size != 4) { \
          break; \
        } \
        const int32_t *code_ptr = (const int32_t*) a[0].b.ptr; \
        return prefix##exit(me, *code_ptr); \
      } \
    } \
    return Object_ERROR_INVALID; \
  }

#endif /* __IENV_INVOKE_H */
