#ifndef __IHWFUSE_H
#define __IHWFUSE_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define IHwFuse_OP_fuseRead 0
#define IHwFuse_OP_fuseWrite 1

static inline int32_t
IHwFuse_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IHwFuse_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
IHwFuse_fuseRead(Object self, uint32_t rowAddress_val, int32_t addrType_val, uint32_t *rowData1_ptr, uint32_t *rowData2_ptr, uint32_t *qfpromApiStatus_ptr)
{
  ObjectArg a[2];
  struct {
    uint32_t m_rowAddress;
    int32_t m_addrType;
  } i;
  a[0].b = (ObjectBuf) { &i, 8 };
  struct {
    uint32_t m_rowData1;
    uint32_t m_rowData2;
    uint32_t m_qfpromApiStatus;
  } o;
  a[1].b = (ObjectBuf) { &o, 12 };
  i.m_rowAddress = rowAddress_val;
  i.m_addrType = addrType_val;

  int32_t result = Object_invoke(self, IHwFuse_OP_fuseRead, a, ObjectCounts_pack(1, 1, 0, 0));

  *rowData1_ptr = o.m_rowData1;
  *rowData2_ptr = o.m_rowData2;
  *qfpromApiStatus_ptr = o.m_qfpromApiStatus;

  return result;
}

static inline int32_t
IHwFuse_fuseWrite(Object self, uint32_t rawRowAddress_val, uint32_t rowData1_val, uint32_t rowData2_val, uint32_t *qfpromApiStatus_ptr)
{
  ObjectArg a[2];
  struct {
    uint32_t m_rawRowAddress;
    uint32_t m_rowData1;
    uint32_t m_rowData2;
  } i;
  a[0].b = (ObjectBuf) { &i, 12 };
  i.m_rawRowAddress = rawRowAddress_val;
  i.m_rowData1 = rowData1_val;
  i.m_rowData2 = rowData2_val;
  a[1].b = (ObjectBuf) { qfpromApiStatus_ptr, sizeof(uint32_t) };

  return Object_invoke(self, IHwFuse_OP_fuseWrite, a, ObjectCounts_pack(1, 1, 0, 0));
}


#endif /* __IHWFUSE_H */
