#ifndef __INSSYSTEMREG_H
#define __INSSYSTEMREG_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights

// Reserved.  Qualcomm Technologies Proprietary and Confidential.

#define INSSystemReg_VBAR_EL1 UINT32_C(0x0)

#define INSSystemReg_ERROR_UNSUPPORTED_SYS_REG_TYPE INT32_C(10)

#define INSSystemReg_OP_GetNSSystemReg 0

static inline int32_t
INSSystemReg_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
INSSystemReg_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
INSSystemReg_GetNSSystemReg(Object self, uint32_t SysReg_val, uint64_t *val_ptr)
{
  ObjectArg a[2];
  a[0].b = (ObjectBuf) { &SysReg_val, sizeof(uint32_t) };
  a[1].b = (ObjectBuf) { val_ptr, sizeof(uint64_t) };

  return Object_invoke(self, INSSystemReg_OP_GetNSSystemReg, a, ObjectCounts_pack(1, 1, 0, 0));
}


#endif /* __INSSYSTEMREG_H */
