#ifndef __ISECUREDISPLAY_H
#define __ISECUREDISPLAY_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define ISecureDisplay_OP_setStopAllowed 0
#define ISecureDisplay_OP_getSession 1

static inline int32_t
ISecureDisplay_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
ISecureDisplay_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
ISecureDisplay_setStopAllowed(Object self, int32_t isAllowed_val)
{
  ObjectArg a[1];
  a[0].b = (ObjectBuf) { &isAllowed_val, sizeof(int32_t) };

  return Object_invoke(self, ISecureDisplay_OP_setStopAllowed, a, ObjectCounts_pack(1, 0, 0, 0));
}

static inline int32_t
ISecureDisplay_getSession(Object self, uint32_t *sessionID_ptr)
{
  ObjectArg a[1];
  a[0].b = (ObjectBuf) { sessionID_ptr, sizeof(uint32_t) };

  return Object_invoke(self, ISecureDisplay_OP_getSession, a, ObjectCounts_pack(0, 1, 0, 0));
}


#endif /* __ISECUREDISPLAY_H */
