#ifndef __ITRANSLATEADDR_H
#define __ITRANSLATEADDR_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights

// Reserved.  Qualcomm Technologies Proprietary and Confidential.

#define ITranslateAddr_EL1_Read UINT32_C(0x0)
#define ITranslateAddr_EL1_Write UINT32_C(0x1)
#define ITranslateAddr_EL0_Read UINT32_C(0x2)
#define ITranslateAddr_EL0_Write UINT32_C(0x3)

#define ITranslateAddr_ERROR_UNSUPPORTED_TRANSLATION_TYPE INT32_C(10)
#define ITranslateAddr_ERROR_TRANSLATION_FAULT INT32_C(11)

#define ITranslateAddr_OP_getPA 0

static inline int32_t
ITranslateAddr_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
ITranslateAddr_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
ITranslateAddr_getPA(Object self, uint32_t translationMethod_val, uint64_t VA_val, uint64_t *PA_ptr)
{
  ObjectArg a[2];
  struct {
    uint64_t m_VA;
    uint32_t m_translationMethod;
  } i;
  a[0].b = (ObjectBuf) { &i, 12 };
  i.m_translationMethod = translationMethod_val;
  i.m_VA = VA_val;
  a[1].b = (ObjectBuf) { PA_ptr, sizeof(uint64_t) };

  return Object_invoke(self, ITranslateAddr_OP_getPA, a, ObjectCounts_pack(1, 1, 0, 0));
}


#endif /* __ITRANSLATEADDR_H */
