#ifndef __IUPTIME_H
#define __IUPTIME_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

/* Copyright (c) 2015-2016 Qualcomm Technologies, Inc.  All Rights Reserved.
   Qualcomm Technologies Proprietary and Confidential. */

/**
 * @brief Get up time from bootup
 *
*/

#define IUptime_OP_getUptime 0
#define IUptime_OP_getUptimeUS 1

static inline int32_t
IUptime_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IUptime_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
IUptime_getUptime(Object self, uint64_t *upTimeMS_ptr)
{
  ObjectArg a[1];
  a[0].b = (ObjectBuf) { upTimeMS_ptr, sizeof(uint64_t) };

  return Object_invoke(self, IUptime_OP_getUptime, a, ObjectCounts_pack(0, 1, 0, 0));
}

static inline int32_t
IUptime_getUptimeUS(Object self, uint64_t *upTimeUS_ptr)
{
  ObjectArg a[1];
  a[0].b = (ObjectBuf) { upTimeUS_ptr, sizeof(uint64_t) };

  return Object_invoke(self, IUptime_OP_getUptimeUS, a, ObjectCounts_pack(0, 1, 0, 0));
}


#endif /* __IUPTIME_H */
