# Auto-generated by /mnt/workspace/test/test-6786567c99ebd2f3360c32c104d001ce6a998a4d-6786567c99ebd2f3360c32c104d001ce6a998a4d/boot_images/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/mnt/workspace/test/test-6786567c99ebd2f3360c32c104d001ce6a998a4d-6786567c99ebd2f3360c32c104d001ce6a998a4d/boot_images
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/mnt/workspace/test/test-6786567c99ebd2f3360c32c104d001ce6a998a4d-6786567c99ebd2f3360c32c104d001ce6a998a4d/boot_images/BaseTools
fi
if [ -e /mnt/workspace/test/test-6786567c99ebd2f3360c32c104d001ce6a998a4d-6786567c99ebd2f3360c32c104d001ce6a998a4d/boot_images/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//mnt/workspace/test/test-6786567c99ebd2f3360c32c104d001ce6a998a4d-6786567c99ebd2f3360c32c104d001ce6a998a4d/boot_images/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/mnt/workspace/test/test-6786567c99ebd2f3360c32c104d001ce6a998a4d-6786567c99ebd2f3360c32c104d001ce6a998a4d/boot_images/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
