/*===========================================================================

FILE:        ul_data.c

DESCRIPTION: This file implements the target-specific NPA Bus subnodes

   Copyright (c) 2016 Qualcomm Technologies Incorporated.
             All Rights Reserved
             QUALCOMM Proprietary/GTDR
-------------------------------------------------------------------------------

$Header: //components/rel/core.qdsp6/1.0.c2/systemdrivers/icb/src/660/cdsp/ul_data.c#1 $ 
$DateTime: 2020/02/10 01:57:30 $
$Author: pwbldsvc $
$Change: 22511909 $

                      EDIT HISTORY FOR FILE

 Autogenerated for target: Cdsp
 This file was generated using Autogen script: 
 gen.py

 when         who     what, where, why
 ----------   ---     -----------------------------------------------------------
 2016/09/12 Autogen  Autogenerated version

=============================================================================*/
#include "npa.h"
#include "npa_resource.h"
#include "npa_log.h"
#include "ul_i.h"
#include "ul_tree.h"
#include "icb_soc_data.h"

/*============================================================================
                          DEFINES
============================================================================*/
/*============================================================================
                   INTERNAL DATA DECLARATIONS
============================================================================*/
/*============================================================================
                        AXI CONFIG DECLARATIONS
============================================================================*/

/****************************************************************************/
/*                              BUSES                                       */
/****************************************************************************/
/**** Bus: bimc ****/
static HAL_bimc_InfoType bimc_hal_info =
{
  0, /* Base address */
  19200, /* QoS frequency */
};

static const char *bus_bimc_clk_names[1] =
{
  "/clk/bimc",
};

static npa_client_handle bus_bimc_clk_clients[1] = {0};

static icb_bus_def_type bimc_bus =
{
  "+BIMC", /* HWIO base name */
  false, /* remote node? */ 
  0, /* base address */
  0x5A000, /* HWIO region size */
  ICB_BUS_BIMC, /* Bus type */
  0, /* Address width */
  4, /* Data width */
  (void *)&bimc_hal_info, /* Bus info structure */
  1,    /* Config clock info */
  bus_bimc_clk_names,
  bus_bimc_clk_clients,
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  {
    ICB_AGG_SCHEME_0,
    153,
    100,
  },
};

/****************************************************************************/
/*                              SLAVES                                      */
/****************************************************************************/
/**** Slave: ebi ****/
/* slave port ids */
static uint32_t cfg_slave_ebi_ports[2] =
{
  0, /* port 0 */
  1, /* port 1 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_ebi =
{
  ICBID_SLAVE_EBI1, /* slaveId */
  &bimc_bus, /* pBus */
  2, /* Number of ports */
  cfg_slave_ebi_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  2, /* Number of ports for aggregation purposes */
};

/**** Slave: hmss_l3 ****/
/* slave port ids */
static uint32_t cfg_slave_hmss_l3_ports[1] =
{
  2, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_hmss_l3 =
{
  ICBID_SLAVE_HMSS_L3, /* slaveId */
  &bimc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_hmss_l3_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/****************************************************************************/
/*                              MASTERS                                     */
/****************************************************************************/
/**** Master: cdsp_proc ****/
/* master port ids */
static uint32_t cfg_master_cdsp_proc_ports[1] =
{
  6, /* port 0 */
};

static uint32_t cfg_master_cdsp_proc_qos_ports[1] =
{
  6, /* port 0 */
};

/* master port default settings */
static icb_bimc_master_defaults_type cfg_master_cdsp_proc_defaults =
{
  /* BIMC ClockGate */
  {
    true, /* Core clock gating */ 
    true,  /* Arb clock gating */
    true, /* Port clock gating */
  },
  /* BIMC Request Type */
  ICB_BW_REQ_TYPE_DEFAULT,
  /* BIMC Mode */
  {BIMC_QOS_MODE_BYPASS},
  /* BIMC Priority */
  {
    /* Fixed priority - unused */
    {
      0,
      0,
      0,
    },
  },
  /* BIMC Threshold */
  0, /* No threshold. */
};

/* master definition */
static icb_master_def_type cfg_master_cdsp_proc =
{
  ICBID_MASTER_CDSP_PROC, /* master id */
  &bimc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_cdsp_proc_ports, /* pPortIds */
  cfg_master_cdsp_proc_qos_ports, /* pQosPortIds */
  false, /* remote node? */ 
  10000, /* default window size */
  &cfg_master_cdsp_proc_defaults, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  2, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/****************************************************************************/
/*                              LISTS                                       */
/****************************************************************************/
/* List of buses */
const uint32 u32cfg_bus_list_size   = 1;
icb_bus_def_type *cfg_bus_list[1] = 
{
  &bimc_bus,
};

/* List of slaves */
const uint32 u32cfg_slave_list_size   = 2;
icb_slave_def_type *cfg_slave_list[2] = 
{
  &cfg_slave_ebi,
  &cfg_slave_hmss_l3,
};

/* List of masters */
const uint32 u32cfg_master_list_size   = 1;
icb_master_def_type *cfg_master_list[1] = 
{
  &cfg_master_cdsp_proc,
};

/* List of configuration clocks */
const uint32 u32ul_cfg_clk_node_list_size   = 1;
const char *ul_cfg_clock_node_list[] =
{
  "/clk/bimc",
};

/* TCSR definitions for port halting */
HAL_tcsr_InfoType *cfg_tcsr_info = NULL;

/*============================================================================
                        TOPOLOGY ROUTE DECLARATIONS
============================================================================*/

/*****************************************************/
/*                       bimc                                      */
/*****************************************************/
/* Masters */
/* CDSP_PROC */
static ul_clock_type master_cdsp_proc_clks[1] =
{
  {
    "/clk/bimc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_cdsp_proc =
{
  /* Master Data */
  "/icb/master/cdsp_proc",
  ICBID_MASTER_CDSP_PROC,                   /* External Master ID */
  4,
  1,
  master_cdsp_proc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_cdsp_proc,
    NULL,
  },
  &cfg_master_cdsp_proc,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_cdsp_proc,
    NULL,
  },
};

/* Slaves */
/* EBI */
static ul_clock_type slave_ebi_slv_clks[1] =
{
  {
    "/clk/bimc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_ebi =
{
  /* Slave Data */
  "/icb/slave/ebi",
  ICBID_SLAVE_EBI1,                        /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_ebi_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_ebi,
    NULL,
  },
  &cfg_slave_ebi
};

/* HMSS_L3 */
static ul_clock_type slave_hmss_l3_slv_clks[1] =
{
  {
    "/clk/bimc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_hmss_l3 =
{
  /* Slave Data */
  "/icb/slave/hmss_l3",
  ICBID_SLAVE_HMSS_L3,                     /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_hmss_l3_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_hmss_l3,
    NULL,
  },
  &cfg_slave_hmss_l3
};

/* Define the valid routes  */
static ul_pair_type route_cdsp_proc_ebi_list_array[1] =
{
  {
    &master_cdsp_proc,
    &slave_ebi
  },
};
static ul_route_list_type route_cdsp_proc_ebi_list =
{
  1,
  route_cdsp_proc_ebi_list_array
};
static ul_pair_type route_cdsp_proc_hmss_l3_list_array[1] =
{
  {
    &master_cdsp_proc,
    &slave_hmss_l3
  },
};
static ul_route_list_type route_cdsp_proc_hmss_l3_list =
{
  1,
  route_cdsp_proc_hmss_l3_list_array
};

/*============================================================================
                         ROUTE TREE - 2 routes
============================================================================*/
/* Forward declarations */
static ul_treeNodeType route_0x9500000000L_cdsp_proc_ebi_node;
static ul_treeNodeType route_0x95000000a0L_cdsp_proc_hmss_l3_node;

/* Create the tree */
static ul_treeNodeType route_0x9500000000L_cdsp_proc_ebi_node =
{
  0x9500000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_cdsp_proc_ebi_list,
  NULL,
  &route_0x95000000a0L_cdsp_proc_hmss_l3_node
};
static ul_treeNodeType route_0x95000000a0L_cdsp_proc_hmss_l3_node =
{
  0x95000000a0ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_cdsp_proc_hmss_l3_list,
  NULL,
  NULL
};

/*============================================================================
                   EXTERNAL DATA DECLARATIONS
============================================================================*/
/* Pointer to the root node */
ul_treeNodeType * route_tree_root = 
  &route_0x9500000000L_cdsp_proc_ebi_node;

const uint32 u32ul_arb_master_list_size   = 1;
ul_master_data_type *ul_arb_master_list[] =
{
  &master_cdsp_proc,
};

const uint32 u32ul_arb_slave_list_size   = 2;
ul_slave_data_type *ul_arb_slave_list[] =
{
  &slave_ebi,
  &slave_hmss_l3,
};

/* Have to make the array size a const so we can export it */
const uint32 u32ul_arb_clk_node_list_size   = 1;
const char *ul_arb_clock_node_list[] =
{
  "/clk/bimc",
};

