#ifndef __STORAGE_DIAG_MSG_H__
#define __STORAGE_DIAG_MSG_H__

#include "storage_diag_config_i.h"
#include "msg.h"

#if defined (STORAGE_DIAG_MPSS_BUILD)
  #define STORAGE_DIAG_PROC_NAME "MPSS "
#elif defined (STORAGE_DIAG_ADSP_BUILD)
  #define STORAGE_DIAG_PROC_NAME "ADSP "
#elif defined (STORAGE_DIAG_SENSORS_BUILD)
  #define STORAGE_DIAG_PROC_NAME "SNSR "
#elif defined (STORAGE_DIAG_SPARROW_BUILD)
  #define STORAGE_DIAG_PROC_NAME "APSS "
#else
  #define STORAGE_DIAG_PROC_NAME " "
#endif

  #define STORAGE_DIAG_MSG_ERROR_0(a) \
          MSG(MSG_SSID_RFS_ACCESS,MSG_LEGACY_ERROR,STORAGE_DIAG_PROC_NAME a)
  #define STORAGE_DIAG_MSG_ERROR_1(a,b) \
          MSG_1(MSG_SSID_RFS_ACCESS,MSG_LEGACY_ERROR,STORAGE_DIAG_PROC_NAME a,b)
  #define STORAGE_DIAG_MSG_ERROR_2(a,b,c) \
          MSG_2(MSG_SSID_RFS_ACCESS,MSG_LEGACY_ERROR,STORAGE_DIAG_PROC_NAME a,b,c)
  #define STORAGE_DIAG_MSG_ERROR_3(a,b,c,d) \
          MSG_3(MSG_SSID_RFS_ACCESS,MSG_LEGACY_ERROR,STORAGE_DIAG_PROC_NAME a,b,c,d)

  #define STORAGE_DIAG_MSG_HIGH_0(a) \
          MSG(MSG_SSID_RFS_ACCESS,MSG_LEGACY_HIGH,STORAGE_DIAG_PROC_NAME a)
  #define STORAGE_DIAG_MSG_HIGH_1(a,b) \
          MSG_1(MSG_SSID_RFS_ACCESS,MSG_LEGACY_HIGH,STORAGE_DIAG_PROC_NAME a,b)
  #define STORAGE_DIAG_MSG_HIGH_2(a,b,c) \
          MSG_2(MSG_SSID_RFS_ACCESS,MSG_LEGACY_HIGH,STORAGE_DIAG_PROC_NAME a,b,c)
  #define STORAGE_DIAG_MSG_HIGH_3(a,b,c,d) \
          MSG_3(MSG_SSID_RFS_ACCESS,MSG_LEGACY_HIGH,STORAGE_DIAG_PROC_NAME a,b,c,d)

  #define STORAGE_DIAG_MSG_MED_0(a) \
          MSG(MSG_SSID_RFS_ACCESS,MSG_LEGACY_MED,STORAGE_DIAG_PROC_NAME a)
  #define STORAGE_DIAG_MSG_MED_1(a,b) \
          MSG_1(MSG_SSID_RFS_ACCESS,MSG_LEGACY_MED,STORAGE_DIAG_PROC_NAME a,b)
  #define STORAGE_DIAG_MSG_MED_2(a,b,c) \
          MSG_2(MSG_SSID_RFS_ACCESS,MSG_LEGACY_MED,STORAGE_DIAG_PROC_NAME a,b,c)
  #define STORAGE_DIAG_MSG_MED_3(a,b,c,d) \
          MSG_3(MSG_SSID_RFS_ACCESS,MSG_LEGACY_MED,STORAGE_DIAG_PROC_NAME a,b,c,d)

  #define STORAGE_DIAG_MSG_LOW_0(a) \
          MSG(MSG_SSID_RFS_ACCESS,MSG_LEGACY_LOW,STORAGE_DIAG_PROC_NAME a)
  #define STORAGE_DIAG_MSG_LOW_1(a,b) \
          MSG_1(MSG_SSID_RFS_ACCESS,MSG_LEGACY_LOW,STORAGE_DIAG_PROC_NAME a,b)
  #define STORAGE_DIAG_MSG_LOW_2(a,b,c) \
          MSG_2(MSG_SSID_RFS_ACCESS,MSG_LEGACY_LOW,STORAGE_DIAG_PROC_NAME a,b,c)
  #define STORAGE_DIAG_MSG_LOW_3(a,b,c,d) \
          MSG_3(MSG_SSID_RFS_ACCESS,MSG_LEGACY_LOW,STORAGE_DIAG_PROC_NAME a,b,c,d)

  #define STORAGE_DIAG_MSG_STRING_1(a,b) \
          MSG_SPRINTF_1(MSG_SSID_RFS_ACCESS,MSG_LEGACY_HIGH,STORAGE_DIAG_PROC_NAME a,b)


#endif /* __STORAGE_DIAG_MSG_H__*/
