/**
 * @file ddr_status_reg.c
 * @brief
 * DDR Status Register logging file for DDR driver.
 */
/*==============================================================================
                                EDIT HISTORY

$Header: //components/rel/rpm.bf/1.8/core/boot/ddr/hw/sdm660/ddr_status_reg.c#3 $
$DateTime: 2017/03/27 22:56:10 $
$Author: pwbldsvc $
================================================================================
when       who     what, where, why
--------   ---     -------------------------------------------------------------
03/02/17   mrr     Added DDR CC register for dump in case of crash
04/23/14   sr      Initial version.
================================================================================
                   Copyright 2014, 2017 Qualcomm Technologies Incorporated
                              All Rights Reserved
                     Qualcomm Confidential and Proprietary
==============================================================================*/
/*==============================================================================
                                  INCLUDES
==============================================================================*/
#include "ddr_common.h"
#include "ddr_drivers.h"
#include "ddr_params.h"
#include "ddr_target.h"
#include "HAL_SNS_DDR.h"
#include "ddr_status_reg.h"
#include "bimc_rpm.h"
#include "ddr_hwio.h"
#include "ddrss_rpm.h"



/*==============================================================================
                                  MACROS
==============================================================================*/

/* -----------------------------------------------------------------------
**                           DATA
** ----------------------------------------------------------------------- */

/* This array contain DDR BIMC/PHY register address ,
 * this list may shrink and grow dependending upon the availability of space in RPM codeRAM for other important struct elements in the big Struct DDR_STRUCT & 
 * this list is flexible , one can edit and update the list and ensure to match it with corresponding struct element 
 * resides in ddr_status_reg.h file */

const uint32 ddr_status_reg_addr[] = {
HWIO_SCMO_CFG_RCH_STATUS_ADDR(REG_OFFSET_SCMO(0)),
HWIO_SCMO_CFG_RCH_STATUS_ADDR(REG_OFFSET_SCMO(1)),
HWIO_SCMO_CFG_WCH_STATUS_ADDR(REG_OFFSET_SCMO(0)),
HWIO_SCMO_CFG_WCH_STATUS_ADDR(REG_OFFSET_SCMO(1)),
HWIO_SCMO_CFG_CMD_BUF_STATUS_ADDR(REG_OFFSET_SCMO(0)),
HWIO_SCMO_CFG_CMD_BUF_STATUS_ADDR(REG_OFFSET_SCMO(1)),
HWIO_DPE_DRAM_STATUS_0_ADDR(REG_OFFSET_DPE(0)),
HWIO_DPE_DRAM_STATUS_0_ADDR(REG_OFFSET_DPE(1)),
HWIO_DPE_MEMC_STATUS_0_ADDR(REG_OFFSET_DPE(0)),
HWIO_DPE_MEMC_STATUS_0_ADDR(REG_OFFSET_DPE(1)),

/* ABORT MODE LOGGING */
HWIO_MCCC_REGS_CLK_PERIOD_ADDR(REG_OFFSET_MCCC),
HWIO_DDR_CC_MCCC_DDRCC_MCCC_TOP_STATUS_ADDR(REG_OFFSET_DDR_PHY_CH(0)+SEQ_DDR_CC_MCCC_DDRCC_MCCC_OFFSET),
HWIO_MCCC_REGS_FREQ_SWITCH_UPDATE_ADDR(REG_OFFSET_MCCC),

HWIO_DDR_CC_DDRCC_PLLCTRL_CLK_SWITCH_STATUS_ADDR(REG_OFFSET_DDR_PHY_CH(0)+ DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_PLLCTRL_STATUS_ADDR(REG_OFFSET_DDR_PHY_CH(0)+ DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_PLL0_STATUS_ADDR(REG_OFFSET_DDR_PHY_CH(0)+ DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_PLL1_STATUS_ADDR(REG_OFFSET_DDR_PHY_CH(0)+ DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_DLL0_STATUS_ADDR(REG_OFFSET_DDR_PHY_CH(0)+ DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_DLL1_STATUS_ADDR(REG_OFFSET_DDR_PHY_CH(0)+ DDR_CC_OFFSET),

HWIO_MCCC_CH_REGS_FSC_STATUS0_ADDR(REG_OFFSET_MCCC_CH(0)),
HWIO_MCCC_CH_REGS_FSC_STATUS3_ADDR(REG_OFFSET_MCCC_CH(0)),
HWIO_MCCC_CH_REGS_FSC_STATUS0_ADDR(REG_OFFSET_MCCC_CH(1)),
HWIO_MCCC_CH_REGS_FSC_STATUS3_ADDR(REG_OFFSET_MCCC_CH(1)),
HWIO_DDR_CC_DDRCC_PLLCTRL_GCC_CTRL_ADDR(REG_OFFSET_DDR_PHY_CH(0)+ DDR_CC_OFFSET),

HWIO_SHKE_MREG_RDATA_STATUS_ADDR(REG_OFFSET_SHKE(0)),
HWIO_DPE_INTERRUPT_STATUS_ADDR(REG_OFFSET_DPE(0)),
HWIO_SHKE_DRAM_STATUS_ADDR(REG_OFFSET_SHKE(0)),
HWIO_SHKE_PERIODIC_MRR_RDATA_RANK1_U_ADDR(REG_OFFSET_SHKE(0)),
HWIO_SHKE_PERIODIC_MRR_RDATA_RANK1_L_ADDR(REG_OFFSET_SHKE(0)),
HWIO_SHKE_PERIODIC_MRR_RDATA_RANK0_U_ADDR(REG_OFFSET_SHKE(0)),
HWIO_SHKE_PERIODIC_MRR_RDATA_RANK0_L_ADDR(REG_OFFSET_SHKE(0)),
HWIO_SHKE_MREG_RDATA_STATUS_ADDR(REG_OFFSET_SHKE(1)),
HWIO_DPE_INTERRUPT_STATUS_ADDR(REG_OFFSET_DPE(1)),
HWIO_SHKE_DRAM_STATUS_ADDR(REG_OFFSET_SHKE(1)),
HWIO_SHKE_PERIODIC_MRR_RDATA_RANK1_U_ADDR(REG_OFFSET_SHKE(1)),
HWIO_SHKE_PERIODIC_MRR_RDATA_RANK1_L_ADDR(REG_OFFSET_SHKE(1)),
HWIO_SHKE_PERIODIC_MRR_RDATA_RANK0_U_ADDR(REG_OFFSET_SHKE(1)),
HWIO_SHKE_PERIODIC_MRR_RDATA_RANK0_L_ADDR(REG_OFFSET_SHKE(1)),

0

#if 0  // this needs to be uncommented depending upon the codeRAM DDR_STRUCT size availability .

/* BIMC MISC */
HWIO_BIMC_DFIN_LP_CFG_ADDR(REG_OFFSET_GLOBAL0,0),
HWIO_BIMC_DFIN_LP_CFG_ADDR(REG_OFFSET_GLOBAL0,1),
HWIO_BIMC_DDR_CHN_HFSC_STATUS_ADDR(REG_OFFSET_GLOBAL0,0),
HWIO_BIMC_DDR_CHN_HFSC_STAGE1_CTRL_ADDR(REG_OFFSET_GLOBAL0,0),
HWIO_BIMC_DDR_CHN_HFSC_STAGE2_CTRL_ADDR(REG_OFFSET_GLOBAL0,0),
HWIO_BIMC_DDR_CHN_HFSC_STATUS_ADDR(REG_OFFSET_GLOBAL0,1),
HWIO_BIMC_DDR_CHN_HFSC_STAGE1_CTRL_ADDR(REG_OFFSET_GLOBAL0,1),
HWIO_BIMC_DDR_CHN_HFSC_STAGE2_CTRL_ADDR(REG_OFFSET_GLOBAL0,1),

/*DDR0_SCMO _ADDR, DDR1_SCMO */
HWIO_SCMO_INTERRUPT_STATUS_ADDR(REG_OFFSET_SCMO(0)),
HWIO_SCMO_ESYN_ADDR_ADDR(REG_OFFSET_SCMO(0)),
HWIO_SCMO_ESYN_APACKET_0_ADDR(REG_OFFSET_SCMO(0)),
HWIO_SCMO_ESYN_APACKET_1_ADDR(REG_OFFSET_SCMO(0)),
HWIO_SCMO_ESYN_APACKET_2_ADDR(REG_OFFSET_SCMO(0)),
HWIO_SCMO_SLV_STATUS_ADDR(REG_OFFSET_SCMO(0)),
HWIO_SCMO_CMD_BUF_STATUS_ADDR(REG_OFFSET_SCMO(0)),
HWIO_SCMO_RCH_STATUS_ADDR(REG_OFFSET_SCMO(0)),
HWIO_SCMO_WCH_STATUS_ADDR(REG_OFFSET_SCMO(0)),
HWIO_SCMO_FSP_STATUS_ADDR(REG_OFFSET_SCMO(0)),

HWIO_SCMO_INTERRUPT_STATUS_ADDR(REG_OFFSET_SCMO(1)),
HWIO_SCMO_ESYN_ADDR_ADDR(REG_OFFSET_SCMO(1)),
HWIO_SCMO_ESYN_APACKET_0_ADDR(REG_OFFSET_SCMO(1)),
HWIO_SCMO_ESYN_APACKET_1_ADDR(REG_OFFSET_SCMO(1)),
HWIO_SCMO_ESYN_APACKET_2_ADDR(REG_OFFSET_SCMO(1)),
HWIO_SCMO_SLV_STATUS_ADDR(REG_OFFSET_SCMO(1)),
HWIO_SCMO_CMD_BUF_STATUS_ADDR(REG_OFFSET_SCMO(1)),
HWIO_SCMO_RCH_STATUS_ADDR(REG_OFFSET_SCMO(1)),
HWIO_SCMO_WCH_STATUS_ADDR(REG_OFFSET_SCMO(1)),
HWIO_SCMO_FSP_STATUS_ADDR(REG_OFFSET_SCMO(1)),

/*DDR0_DPE _ADDR, DDR1_DPE*/
HWIO_DPE_INTERRUPT_STATUS_ADDR(REG_OFFSET_DPE(0)),
HWIO_DPE_DQCAL_STATUS0_RANK1_ADDR(REG_OFFSET_DPE(0)),
HWIO_DPE_DQCAL_STATUS1_RANK1_ADDR(REG_OFFSET_DPE(0)),
HWIO_DPE_DQCAL_STATUS2_RANK1_ADDR(REG_OFFSET_DPE(0)),
HWIO_DPE_DQCAL_STATUS0_RANK0_ADDR(REG_OFFSET_DPE(0)),
HWIO_DPE_DQCAL_STATUS1_RANK0_ADDR(REG_OFFSET_DPE(0)),
HWIO_DPE_DQCAL_STATUS2_RANK0_ADDR(REG_OFFSET_DPE(0)),
HWIO_DPE_DRAM_STATUS_0_ADDR(REG_OFFSET_DPE(0)),
HWIO_DPE_MEMC_STATUS_1_ADDR(REG_OFFSET_DPE(0)),
HWIO_DPE_MEMC_STATUS_2_ADDR(REG_OFFSET_DPE(0)),

HWIO_DPE_INTERRUPT_STATUS_ADDR(REG_OFFSET_DPE(1)),
HWIO_DPE_DQCAL_STATUS0_RANK1_ADDR(REG_OFFSET_DPE(1)),
HWIO_DPE_DQCAL_STATUS1_RANK1_ADDR(REG_OFFSET_DPE(1)),
HWIO_DPE_DQCAL_STATUS2_RANK1_ADDR(REG_OFFSET_DPE(1)),
HWIO_DPE_DQCAL_STATUS0_RANK0_ADDR(REG_OFFSET_DPE(1)),
HWIO_DPE_DQCAL_STATUS1_RANK0_ADDR(REG_OFFSET_DPE(1)),
HWIO_DPE_DQCAL_STATUS2_RANK0_ADDR(REG_OFFSET_DPE(1)),
HWIO_DPE_DRAM_STATUS_0_ADDR(REG_OFFSET_DPE(1)),
HWIO_DPE_MEMC_STATUS_1_ADDR(REG_OFFSET_DPE(1)),
HWIO_DPE_MEMC_STATUS_2_ADDR(REG_OFFSET_DPE(1)),


/*DDR0_SHKE _ADDR, DDR1_SHKE*/
HWIO_SHKE_DRAM_STATUS_ADDR(REG_OFFSET_SHKE(0)), 
HWIO_SHKE_PERIODIC_MRR_RDATA_RANK1_U_ADDR(REG_OFFSET_SHKE(0)),
HWIO_SHKE_PERIODIC_MRR_RDATA_RANK1_L_ADDR(REG_OFFSET_SHKE(0)),
HWIO_SHKE_PERIODIC_MRR_RDATA_RANK0_U_ADDR(REG_OFFSET_SHKE(0)),
HWIO_SHKE_PERIODIC_MRR_RDATA_RANK0_L_ADDR(REG_OFFSET_SHKE(0)),

HWIO_SHKE_DRAM_STATUS_ADDR(REG_OFFSET_SHKE(1)),
HWIO_SHKE_PERIODIC_MRR_RDATA_RANK1_U_ADDR(REG_OFFSET_SHKE(1)),
HWIO_SHKE_PERIODIC_MRR_RDATA_RANK1_L_ADDR(REG_OFFSET_SHKE(1)),
HWIO_SHKE_PERIODIC_MRR_RDATA_RANK0_U_ADDR(REG_OFFSET_SHKE(1)),
HWIO_SHKE_PERIODIC_MRR_RDATA_RANK0_L_ADDR(REG_OFFSET_SHKE(1)),


/*HWIO_CH0_CA0_DDR_PHY */
HWIO_DDR_PHY_DDRPHY_IOCTLR_TIMER_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_DCC_STATUS_0_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMRX_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_BISC_TRAINING_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWRLVL_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRD_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRDT2_I0_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRCW_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCMSTR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_0_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA0_DDR_PHY_OFFSET),


/*HWIO_CH0_CA1_DDR_PHY*/

HWIO_DDR_PHY_DDRPHY_IOCTLR_TIMER_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_DCC_STATUS_0_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMRX_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_BISC_TRAINING_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWRLVL_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRD_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRDT2_I0_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRCW_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCMSTR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_0_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+CA1_DDR_PHY_OFFSET),


/*HWIO_CH1_CA0_DDR_PHY */

HWIO_DDR_PHY_DDRPHY_IOCTLR_TIMER_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_DCC_STATUS_0_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMRX_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_BISC_TRAINING_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWRLVL_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRD_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRDT2_I0_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRCW_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCMSTR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_0_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA0_DDR_PHY_OFFSET),

/*HWIO_CH1_CA1_DDR_PHY */

HWIO_DDR_PHY_DDRPHY_IOCTLR_TIMER_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_DCC_STATUS_0_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMRX_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_BISC_TRAINING_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWRLVL_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRD_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRDT2_I0_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRCW_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCMSTR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_0_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+CA1_DDR_PHY_OFFSET),


/* DDRCC HWIO_CH0/HWIO_CH1 */

HWIO_DDR_CC_DDRCC_TOP_CTRL_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_PLLCTRL_CLK_SWITCH_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_PLLCTRL_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_DLLCTRL_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_TXPHYCTRL_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_TXMCCTRL_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_PLL0_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_PLL1_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_TX0_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_TX1_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_TXPHY_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_DLL0_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_DLL1_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_DLLHIST_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DDR_CC_OFFSET),

HWIO_DDR_CC_DDRCC_TOP_CTRL_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_PLLCTRL_CLK_SWITCH_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_PLLCTRL_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_DLLCTRL_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_TXPHYCTRL_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_TXMCCTRL_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DDR_CC_OFFSET), 
HWIO_DDR_CC_DDRCC_PLL0_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_PLL1_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_TX0_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_TX1_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_TXPHY_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_DLL0_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_DLL1_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DDR_CC_OFFSET),
HWIO_DDR_CC_DDRCC_DLLHIST_STATUS_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DDR_CC_OFFSET),


/* DQ0/DQ1/DQ2/DQ3 HWIO_CH0/HWIO_CH1 */

HWIO_DDR_PHY_DDRPHY_TOP_CTRL_0_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_1_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_2_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_3_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_4_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_IOCTLR_CTRL_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_DCC_STATUS_0_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMRX_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_BISC_TRAINING_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWRLVL_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRD_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRDT2_I0_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRCW_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCMSTR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ0_DDR_PHY_OFFSET),


HWIO_DDR_PHY_DDRPHY_TOP_CTRL_0_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_1_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_2_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_3_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_4_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_IOCTLR_CTRL_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_DCC_STATUS_0_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMRX_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_BISC_TRAINING_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWRLVL_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRD_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRDT2_I0_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRCW_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCMSTR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ1_DDR_PHY_OFFSET),

HWIO_DDR_PHY_DDRPHY_TOP_CTRL_0_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_1_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_2_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_3_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_4_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_IOCTLR_CTRL_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_DCC_STATUS_0_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMRX_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_BISC_TRAINING_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWRLVL_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRD_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRDT2_I0_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRCW_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCMSTR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ2_DDR_PHY_OFFSET),


HWIO_DDR_PHY_DDRPHY_TOP_CTRL_0_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_1_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_2_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_3_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_4_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_IOCTLR_CTRL_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_DCC_STATUS_0_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMRX_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_BISC_TRAINING_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWRLVL_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRD_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRDT2_I0_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRCW_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCMSTR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(1)+DQ3_DDR_PHY_OFFSET),


HWIO_DDR_PHY_DDRPHY_TOP_CTRL_0_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_1_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_2_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_3_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_4_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_IOCTLR_CTRL_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_DCC_STATUS_0_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMRX_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_BISC_TRAINING_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWRLVL_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRD_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRDT2_I0_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRCW_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCMSTR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ0_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ0_DDR_PHY_OFFSET),


HWIO_DDR_PHY_DDRPHY_TOP_CTRL_0_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_1_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_2_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_3_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_4_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_IOCTLR_CTRL_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_DCC_STATUS_0_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMRX_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_BISC_TRAINING_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWRLVL_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRD_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRDT2_I0_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRCW_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCMSTR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ1_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ1_DDR_PHY_OFFSET),

HWIO_DDR_PHY_DDRPHY_TOP_CTRL_0_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_1_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_2_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_3_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_4_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_IOCTLR_CTRL_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_DCC_STATUS_0_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMRX_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_BISC_TRAINING_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWRLVL_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRD_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRDT2_I0_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRCW_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCMSTR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ2_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ2_DDR_PHY_OFFSET),


HWIO_DDR_PHY_DDRPHY_TOP_CTRL_0_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_1_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_2_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_3_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_TOP_CTRL_4_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_IOCTLR_CTRL_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_DCC_STATUS_0_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMRX_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_BISC_TRAINING_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_STATUS_STA_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWRLVL_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCWR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRD_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRDT2_I0_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCRCW_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMCDCMSTR_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ3_DDR_PHY_OFFSET),
HWIO_DDR_PHY_DDRPHY_CMLDO_TOP_CFG_ADDR (REG_OFFSET_DDR_PHY_CH(2)+DQ3_DDR_PHY_OFFSET),
#endif

};  // end of the array with status register addresses .


/* -----------------------------------------------------------------------
**                           FUNCTIONS
** ----------------------------------------------------------------------- */

/* ============================================================================
**  Function : ddr_save_status_regs
** ============================================================================
*/
/*!
*   @brief
*   This function is called before and after pre/post clock/voltage switch to store the
*   status information of the important DDR PHY/BIMC registers .
*
*   @details
*   This function store the status register values, BIMC/PHY status registers ( for pre_clock , pre_voltage switch) in 0th index , 
*   BIMC/PHY status registers ( for post_clock , post_voltage switch) in 1st index of ddr_status_reg field of DDR_STRUCT 
*
*   @param
*   None
*
*   @par Dependencies
*
*   @par Side Effects
*   None
*
*   @retval  None
*
*   @sa None
*/

void ddr_save_status_regs(reg_status_log pre_post)
{
  uint32 i = 0;
  uint32 count = 0;
  uint32 *status_reg_ptr = (uint32*)&ddrsns_share_data->status_registers[(pre_post % 2)];
  ddr_interface_state ddr_status = ddr_get_status();
  
  /* If(dual rank device ) || (single rank device ) */

  if(((ddr_status.sdram0_cs0 == DDR_ACTIVE) &&
     (ddr_status.sdram0_cs1 == DDR_ACTIVE) &&
     (ddr_status.sdram1_cs0 == DDR_ACTIVE) &&
     (ddr_status.sdram1_cs1 == DDR_ACTIVE)) ||
	 
	 ((ddr_status.sdram0_cs0 == DDR_ACTIVE) &&
	 (ddr_status.sdram1_cs0 == DDR_ACTIVE))) {

  	do{
	      *status_reg_ptr = *((uint32*)(ddr_status_reg_addr[i]));
	      status_reg_ptr++;
	      if( pre_post != ERROR_FATAL_0 && pre_post != ERROR_FATAL_1 ){
		      count++;
	      }
	      if ( count == 10 ) break; /* Max 10 registers we can log during clock switch to avoid latency issues */

	  }while(ddr_status_reg_addr[++i] != 0);
  }
}


/* ============================================================================
**  Function : ddr_store_status_regs_error_fatal
** ============================================================================
*/
/*!
*   @brief
*   This function is called before software triggers for watchdog reset
*
*   @details
*   This function is called before software triggers for watchdog reset. This 
*   function will take a snapshot of the entire bimc and ddrphy register into
*   predetermined code region, overwriting the code segment of ddr driver.
*
*   @param
*   None
*
*   @par Dependencies
*
*   @par Side Effects
*   ddr code segment will be trashed. This is normally safe because this code 
*   should only be called when rpm has already crashed.
*
*   @retval  None
*
*   @sa None
*/

__attribute__((section("ddr_abort_funcs"))) void ddr_store_status_regs_error_fatal(void)
{
    ddr_external_set_ddrss_cfg_clk(TRUE);
    ddr_save_status_regs(ERROR_FATAL_0);
    ddr_save_status_regs(ERROR_FATAL_1);
    ddr_external_set_ddrss_cfg_clk(FALSE);
}

