/*===========================================================================

FILE:        ul_data.c

DESCRIPTION: This file implements the target-specific NPA Bus subnodes

   Copyright (c) 2016 Qualcomm Technologies Incorporated.
             All Rights Reserved
             QUALCOMM Proprietary/GTDR
-------------------------------------------------------------------------------

$Header: //components/rel/core.qdsp6/1.0.c2/systemdrivers/icb/src/8998/slpi/ul_data.c#1 $ 
$DateTime: 2020/02/10 01:57:30 $
$Author: pwbldsvc $
$Change: 22511909 $

                      EDIT HISTORY FOR FILE

 Autogenerated for target: LPASS
 This file was generated using Autogen script: 
 gen.py

 when         who     what, where, why
 ----------   ---     -----------------------------------------------------------
 2015/08/26 Autogen  Autogenerated version

=============================================================================*/
#include "npa.h"
#include "npa_resource.h"
#include "npa_log.h"
#include "ul_i.h"
#include "ul_tree.h"
#include "icb_soc_data.h"

/*============================================================================
                          DEFINES
============================================================================*/
/*============================================================================
                   INTERNAL DATA DECLARATIONS
============================================================================*/
/*============================================================================
                        AXI CONFIG DECLARATIONS
============================================================================*/

/****************************************************************************/
/*                              BUSES                                       */
/****************************************************************************/
/**** Bus: a1noc ****/
static HAL_noc_QosMasterInfoType a1noc_master_info[4] =
{
  {0}, /* unused port 0 */
  {0}, /* unused port 1 */
  {0}, /* unused port 2 */
  {NOC_QOS_ALLOWED_MODE_BYPASS | NOC_QOS_ALLOWED_MODE_FIXED}, /* blsp_2 */
};

static HAL_noc_InfoType a1noc_hal_info =
{
  0,        /* Base address */
  1,     /* Number of masters */
  4, /* Number of masters with QoS */ 
  1,      /* Number of slaves */ 
  4800,         /* QoS frequency */ 
  a1noc_master_info, /* QoS master info */
  false, /* Save/Restore unused here. */
  NULL,
  0,
  NULL,
  NOC_QOS_OFFSET_INVALID, /* NOC layout type */
  0x9000, /* QoS offset */
  0x1000, /* QoS block size */
};

static const char *bus_a1noc_clk_names[1] =
{
  "/clk/agr1",
};

static npa_client_handle bus_a1noc_clk_clients[1] = {0};

static icb_bus_def_type a1noc_bus =
{
  "+A1_NOC_AGGRE1_NOC", /* HWIO base name */
  true, /* remote node? */ 
  0, /* base address */
  0xF000, /* HWIO region size */
  ICB_BUS_NOC, /* Bus type */
  0, /* Address width */
  16, /* Data width */
  (void *)&a1noc_hal_info, /* Bus info structure */
  1,    /* Config clock info */
  bus_a1noc_clk_names,
  bus_a1noc_clk_clients,
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  {
    ICB_AGG_SCHEME_LEGACY,
    0,
    0,
  },
};

/**** Bus: bimc ****/
static HAL_bimc_InfoType bimc_hal_info =
{
  0, /* Base address */
  19200, /* QoS frequency */
};

static const char *bus_bimc_clk_names[1] =
{
  "/clk/bimc",
};

static npa_client_handle bus_bimc_clk_clients[1] = {0};

static icb_bus_def_type bimc_bus =
{
  "+BIMC", /* HWIO base name */
  true, /* remote node? */ 
  0, /* base address */
  0x62000, /* HWIO region size */
  ICB_BUS_BIMC, /* Bus type */
  0, /* Address width */
  8, /* Data width */
  (void *)&bimc_hal_info, /* Bus info structure */
  1,    /* Config clock info */
  bus_bimc_clk_names,
  bus_bimc_clk_clients,
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  {
    ICB_AGG_SCHEME_0,
    153,
    100,
  },
};

/**** Bus: cnoc ****/
static HAL_noc_InfoType cnoc_hal_info =
{
  0,        /* Base address */
  1,     /* Number of masters */
  0, /* Number of masters with QoS */ 
  16,      /* Number of slaves */ 
  19200,         /* QoS frequency */ 
  NULL, /* QoS master info */
  false, /* Save/Restore unused here. */
  NULL,
  0,
  NULL,
  NOC_QOS_OFFSET_LEGACY, /* NOC layout type */
};

static const char *bus_cnoc_clk_names[1] =
{
  "/clk/cnoc",
};

static npa_client_handle bus_cnoc_clk_clients[1] = {0};

static icb_bus_def_type cnoc_bus =
{
  "+CNOC_SERVICE_NETWORK", /* HWIO base name */
  true, /* remote node? */ 
  0, /* base address */
  0x1000, /* HWIO region size */
  ICB_BUS_NOC, /* Bus type */
  0, /* Address width */
  8, /* Data width */
  (void *)&cnoc_hal_info, /* Bus info structure */
  1,    /* Config clock info */
  bus_cnoc_clk_names,
  bus_cnoc_clk_clients,
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  {
    ICB_AGG_SCHEME_0,
    0,
    100,
  },
};

/**** Bus: cr_virt ****/

static icb_bus_def_type cr_virt_bus =
{
  "", /* HWIO base name */
  true, /* remote node? */ 
  0, /* base address */
  0x0, /* HWIO region size */
  ICB_BUS_VIRT, /* Bus type */
  0, /* Address width */
  8, /* Data width */
  NULL, /* Bus info structure */
  0,    /* No config clocks. */
  NULL,
  NULL,
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  {
    ICB_AGG_SCHEME_LEGACY,
    0,
    0,
  },
};

/**** Bus: snoc ****/
static HAL_noc_QosMasterInfoType snoc_master_info[5] =
{
  {NOC_QOS_ALLOWED_MODE_BYPASS | NOC_QOS_ALLOWED_MODE_FIXED | NOC_QOS_ALLOWED_MODE_LIMITER | NOC_QOS_ALLOWED_MODE_REGULATOR}, /* lpass_ahb */
  {0}, /* unused port 1 */
  {0}, /* unused port 2 */
  {0}, /* unused port 3 */
  {NOC_QOS_ALLOWED_MODE_BYPASS | NOC_QOS_ALLOWED_MODE_FIXED | NOC_QOS_ALLOWED_MODE_LIMITER | NOC_QOS_ALLOWED_MODE_REGULATOR}, /* lpass_proc */
};

static HAL_noc_InfoType snoc_hal_info =
{
  0,        /* Base address */
  4,     /* Number of masters */
  5, /* Number of masters with QoS */ 
  6,      /* Number of slaves */ 
  4800,         /* QoS frequency */ 
  snoc_master_info, /* QoS master info */
  false, /* Save/Restore unused here. */
  NULL,
  0,
  NULL,
  NOC_QOS_OFFSET_INVALID, /* NOC layout type */
  0x5000, /* QoS offset */
  0x1000, /* QoS block size */
};

static const char *bus_snoc_clk_names[1] =
{
  "/clk/snoc",
};

static npa_client_handle bus_snoc_clk_clients[1] = {0};

static icb_bus_def_type snoc_bus =
{
  "SYSTEM_NOC", /* HWIO base name */
  false, /* remote node? */ 
  0, /* base address */
  0xC000, /* HWIO region size */
  ICB_BUS_NOC, /* Bus type */
  0, /* Address width */
  16, /* Data width */
  (void *)&snoc_hal_info, /* Bus info structure */
  1,    /* Config clock info */
  bus_snoc_clk_names,
  bus_snoc_clk_clients,
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  {
    ICB_AGG_SCHEME_LEGACY,
    0,
    0,
  },
};

/****************************************************************************/
/*                              SLAVES                                      */
/****************************************************************************/
/**** Slave: a1noc_snoc ****/
/* slave port ids */
static uint32_t cfg_slave_a1noc_snoc_ports[1] =
{
  0, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_a1noc_snoc =
{
  ICBID_SLAVE_A1NOC_SNOC, /* slaveId */
  &a1noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_a1noc_snoc_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: blsp_1 ****/
/* slave port ids */
static uint32_t cfg_slave_blsp_1_ports[1] =
{
  69, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_blsp_1 =
{
  ICBID_SLAVE_BLSP_1, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_blsp_1_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: blsp_2 ****/
/* slave port ids */
static uint32_t cfg_slave_blsp_2_ports[1] =
{
  63, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_blsp_2 =
{
  ICBID_SLAVE_BLSP_2, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_blsp_2_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: clk_ctl ****/
/* slave port ids */
static uint32_t cfg_slave_clk_ctl_ports[1] =
{
  38, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_clk_ctl =
{
  ICBID_SLAVE_CLK_CTL, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_clk_ctl_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: ebi ****/
/* slave port ids */
static uint32_t cfg_slave_ebi_ports[2] =
{
  0, /* port 0 */
  1, /* port 1 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_ebi =
{
  ICBID_SLAVE_EBI1, /* slaveId */
  &bimc_bus, /* pBus */
  2, /* Number of ports */
  cfg_slave_ebi_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  2, /* Number of ports for aggregation purposes */
};

/**** Slave: glm ****/
/* slave port ids */
static uint32_t cfg_slave_glm_ports[1] =
{
  40, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_glm =
{
  ICBID_SLAVE_GLM, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_glm_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: hmss_l3 ****/
/* slave port ids */
static uint32_t cfg_slave_hmss_l3_ports[1] =
{
  2, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_hmss_l3 =
{
  ICBID_SLAVE_HMSS_L3, /* slaveId */
  &bimc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_hmss_l3_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: imem ****/
/* slave port ids */
static uint32_t cfg_slave_imem_ports[1] =
{
  8, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_imem =
{
  ICBID_SLAVE_IMEM, /* slaveId */
  &snoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_imem_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: message_ram ****/
/* slave port ids */
static uint32_t cfg_slave_message_ram_ports[1] =
{
  14, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_message_ram =
{
  ICBID_SLAVE_MESSAGE_RAM, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_message_ram_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: mss_cfg ****/
/* slave port ids */
static uint32_t cfg_slave_mss_cfg_ports[1] =
{
  50, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_mss_cfg =
{
  ICBID_SLAVE_CNOC_MSS, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_mss_cfg_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: pdm ****/
/* slave port ids */
static uint32_t cfg_slave_pdm_ports[1] =
{
  64, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_pdm =
{
  ICBID_SLAVE_PDM, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_pdm_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: pimem ****/
/* slave port ids */
static uint32_t cfg_slave_pimem_ports[1] =
{
  9, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_pimem =
{
  ICBID_SLAVE_PIMEM, /* slaveId */
  &snoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_pimem_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: pmic_arb ****/
/* slave port ids */
static uint32_t cfg_slave_pmic_arb_ports[1] =
{
  8, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_pmic_arb =
{
  ICBID_SLAVE_PMIC_ARB, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_pmic_arb_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: prng ****/
/* slave port ids */
static uint32_t cfg_slave_prng_ports[1] =
{
  20, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_prng =
{
  ICBID_SLAVE_PRNG, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_prng_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: qdss_stm ****/
/* slave port ids */
static uint32_t cfg_slave_qdss_stm_ports[1] =
{
  11, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qdss_stm =
{
  ICBID_SLAVE_QDSS_STM, /* slaveId */
  &snoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qdss_stm_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: sdcc_2 ****/
/* slave port ids */
static uint32_t cfg_slave_sdcc_2_ports[1] =
{
  70, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_sdcc_2 =
{
  ICBID_SLAVE_SDCC_2, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_sdcc_2_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: sdcc_4 ****/
/* slave port ids */
static uint32_t cfg_slave_sdcc_4_ports[1] =
{
  71, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_sdcc_4 =
{
  ICBID_SLAVE_SDCC_4, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_sdcc_4_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: snoc_bimc ****/
/* slave port ids */
static uint32_t cfg_slave_snoc_bimc_ports[2] =
{
  5, /* port 0 */
  6, /* port 1 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_snoc_bimc =
{
  ICBID_SLAVE_SNOC_BIMC, /* slaveId */
  &snoc_bus, /* pBus */
  2, /* Number of ports */
  cfg_slave_snoc_bimc_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  2, /* Number of ports for aggregation purposes */
};

/**** Slave: snoc_cfg ****/
/* slave port ids */
static uint32_t cfg_slave_snoc_cfg_ports[1] =
{
  31, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_snoc_cfg =
{
  ICBID_SLAVE_SNOC_CFG, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_snoc_cfg_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: snoc_cnoc ****/
/* slave port ids */
static uint32_t cfg_slave_snoc_cnoc_ports[1] =
{
  7, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_snoc_cnoc =
{
  ICBID_SLAVE_SNOC_CNOC, /* slaveId */
  &snoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_snoc_cnoc_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: srvc_snoc ****/
/* slave port ids */
static uint32_t cfg_slave_srvc_snoc_ports[1] =
{
  13, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_srvc_snoc =
{
  ICBID_SLAVE_SERVICE_SNOC, /* slaveId */
  &snoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_srvc_snoc_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: tcsr ****/
/* slave port ids */
static uint32_t cfg_slave_tcsr_ports[1] =
{
  30, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_tcsr =
{
  ICBID_SLAVE_TCSR, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_tcsr_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: tlmm_east ****/
/* slave port ids */
static uint32_t cfg_slave_tlmm_east_ports[1] =
{
  76, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_tlmm_east =
{
  ICBID_SLAVE_TLMM_EAST, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_tlmm_east_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: tlmm_north ****/
/* slave port ids */
static uint32_t cfg_slave_tlmm_north_ports[1] =
{
  9, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_tlmm_north =
{
  ICBID_SLAVE_TLMM_NORTH, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_tlmm_north_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: tlmm_west ****/
/* slave port ids */
static uint32_t cfg_slave_tlmm_west_ports[1] =
{
  56, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_tlmm_west =
{
  ICBID_SLAVE_TLMM_WEST, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_tlmm_west_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/****************************************************************************/
/*                              MASTERS                                     */
/****************************************************************************/
/**** Master: a1noc_snoc ****/
/* master port ids */
static uint32_t cfg_master_a1noc_snoc_ports[1] =
{
  7, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_a1noc_snoc =
{
  ICBID_MASTER_A1NOC_SNOC, /* master id */
  &snoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_a1noc_snoc_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: blsp_2 ****/
/* master port ids */
static uint32_t cfg_master_blsp_2_ports[1] =
{
  3, /* port 0 */
};

static uint32_t cfg_master_blsp_2_qos_ports[1] =
{
  3, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_blsp_2 =
{
  ICBID_MASTER_BLSP_2, /* master id */
  &a1noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_blsp_2_ports, /* pPortIds */
  cfg_master_blsp_2_qos_ports, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: lpass_ahb ****/
/* master port ids */
static uint32_t cfg_master_lpass_ahb_ports[1] =
{
  2, /* port 0 */
};

static uint32_t cfg_master_lpass_ahb_qos_ports[1] =
{
  0, /* port 0 */
};

/* master port default settings */
static icb_noc_master_defaults_type cfg_master_lpass_ahb_defaults =
{
  /* NoC Mode */
  NOC_QOS_MODE_FIXED,
  /* NoC Priority */
  {
    1, /* p1 */
    1, /* p0 */
  },
};

/* master definition */
static icb_master_def_type cfg_master_lpass_ahb =
{
  ICBID_MASTER_LPASS_AHB, /* master id */
  &snoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_lpass_ahb_ports, /* pPortIds */
  cfg_master_lpass_ahb_qos_ports, /* pQosPortIds */
  false, /* remote node? */ 
  0, /* default window size */
  &cfg_master_lpass_ahb_defaults, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: lpass_proc ****/
/* master port ids */
static uint32_t cfg_master_lpass_proc_ports[1] =
{
  11, /* port 0 */
};

static uint32_t cfg_master_lpass_proc_qos_ports[1] =
{
  4, /* port 0 */
};

/* master port default settings */
static icb_noc_master_defaults_type cfg_master_lpass_proc_defaults =
{
  /* NoC Mode */
  NOC_QOS_MODE_BYPASS,
};

/* master definition */
static icb_master_def_type cfg_master_lpass_proc =
{
  ICBID_MASTER_LPASS_PROC, /* master id */
  &snoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_lpass_proc_ports, /* pPortIds */
  cfg_master_lpass_proc_qos_ports, /* pQosPortIds */
  false, /* remote node? */ 
  0, /* default window size */
  &cfg_master_lpass_proc_defaults, /* pDefaults */
  NULL, /* pHaltPorts */
  true, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: snoc_bimc ****/
/* master port ids */
static uint32_t cfg_master_snoc_bimc_ports[1] =
{
  3, /* port 0 */
};

static uint32_t cfg_master_snoc_bimc_qos_ports[1] =
{
  3, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_snoc_bimc =
{
  ICBID_MASTER_SNOC_BIMC, /* master id */
  &bimc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_snoc_bimc_ports, /* pPortIds */
  cfg_master_snoc_bimc_qos_ports, /* pQosPortIds */
  true, /* remote node? */ 
  10000, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  2, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: snoc_cfg ****/
/* master port ids */
static uint32_t cfg_master_snoc_cfg_ports[1] =
{
  4, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_snoc_cfg =
{
  ICBID_MASTER_SNOC_CFG, /* master id */
  &snoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_snoc_cfg_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: snoc_cnoc ****/
/* master port ids */
static uint32_t cfg_master_snoc_cnoc_ports[1] =
{
  0, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_snoc_cnoc =
{
  ICBID_MASTER_SNOC_CNOC, /* master id */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_snoc_cnoc_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  false, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/****************************************************************************/
/*                              LISTS                                       */
/****************************************************************************/
/* List of buses */
const uint32 u32cfg_bus_list_size   = 5;
icb_bus_def_type *cfg_bus_list[5] = 
{
  &a1noc_bus,
  &bimc_bus,
  &cnoc_bus,
  &cr_virt_bus,
  &snoc_bus,
};

/* List of slaves */
const uint32 u32cfg_slave_list_size   = 25;
icb_slave_def_type *cfg_slave_list[25] = 
{
  &cfg_slave_a1noc_snoc,
  &cfg_slave_blsp_1,
  &cfg_slave_blsp_2,
  &cfg_slave_clk_ctl,
  &cfg_slave_ebi,
  &cfg_slave_glm,
  &cfg_slave_hmss_l3,
  &cfg_slave_imem,
  &cfg_slave_message_ram,
  &cfg_slave_mss_cfg,
  &cfg_slave_pdm,
  &cfg_slave_pimem,
  &cfg_slave_pmic_arb,
  &cfg_slave_prng,
  &cfg_slave_qdss_stm,
  &cfg_slave_sdcc_2,
  &cfg_slave_sdcc_4,
  &cfg_slave_snoc_bimc,
  &cfg_slave_snoc_cfg,
  &cfg_slave_snoc_cnoc,
  &cfg_slave_srvc_snoc,
  &cfg_slave_tcsr,
  &cfg_slave_tlmm_east,
  &cfg_slave_tlmm_north,
  &cfg_slave_tlmm_west,
};

/* List of masters */
const uint32 u32cfg_master_list_size   = 7;
icb_master_def_type *cfg_master_list[7] = 
{
  &cfg_master_a1noc_snoc,
  &cfg_master_blsp_2,
  &cfg_master_lpass_ahb,
  &cfg_master_lpass_proc,
  &cfg_master_snoc_bimc,
  &cfg_master_snoc_cfg,
  &cfg_master_snoc_cnoc,
};

/* List of configuration clocks */
const uint32 u32ul_cfg_clk_node_list_size   = 4;
const char *ul_cfg_clock_node_list[] =
{
  "/clk/agr1",
  "/clk/bimc",
  "/clk/cnoc",
  "/clk/snoc",
};

/* TCSR definitions for port halting */
HAL_tcsr_InfoType *cfg_tcsr_info = NULL;

/*============================================================================
                        TOPOLOGY ROUTE DECLARATIONS
============================================================================*/

/*****************************************************/
/*                       a1noc                                      */
/*****************************************************/
/* Masters */
/* BLSP_2 */
static ul_clock_type master_blsp_2_clks[1] =
{
  {
    "/clk/agr1",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_blsp_2 =
{
  /* Master Data */
  "/icb/master/blsp_2",
  ICBID_MASTER_BLSP_2,                      /* External Master ID */
  16,
  1,
  master_blsp_2_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_blsp_2,
    NULL,
  },
  &cfg_master_blsp_2,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_blsp_2,
    NULL,
  },
};

/* Slaves */
/* A1NOC_SNOC */
static ul_clock_type slave_a1noc_snoc_slv_clks[1] =
{
  {
    "/clk/agr1",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_a1noc_snoc =
{
  /* Slave Data */
  "/icb/slave/a1noc_snoc",
  ICBID_SLAVE_A1NOC_SNOC,                  /* External Slave ID */
  16,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_a1noc_snoc_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_a1noc_snoc,
    NULL,
  },
  &cfg_slave_a1noc_snoc
};

/*****************************************************/
/*                       bimc                                      */
/*****************************************************/
/* Masters */
/* SNOC_BIMC */
static ul_clock_type master_snoc_bimc_clks[1] =
{
  {
    "/clk/bimc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_snoc_bimc =
{
  /* Master Data */
  "/icb/master/snoc_bimc",
  ICBID_MASTER_SNOC_BIMC,                   /* External Master ID */
  8,
  1,
  master_snoc_bimc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_snoc_bimc,
    NULL,
  },
  &cfg_master_snoc_bimc,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_snoc_bimc,
    NULL,
  },
};

/* Slaves */
/* EBI */
static ul_clock_type slave_ebi_slv_clks[1] =
{
  {
    "/clk/bimc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_ebi =
{
  /* Slave Data */
  "/icb/slave/ebi",
  ICBID_SLAVE_EBI1,                        /* External Slave ID */
  8,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_ebi_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_ebi,
    NULL,
  },
  &cfg_slave_ebi
};

/* HMSS_L3 */
static ul_clock_type slave_hmss_l3_slv_clks[1] =
{
  {
    "/clk/bimc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_hmss_l3 =
{
  /* Slave Data */
  "/icb/slave/hmss_l3",
  ICBID_SLAVE_HMSS_L3,                     /* External Slave ID */
  8,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_hmss_l3_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_hmss_l3,
    NULL,
  },
  &cfg_slave_hmss_l3
};

/*****************************************************/
/*                       cnoc                                      */
/*****************************************************/
/* Masters */
/* SNOC_CNOC */
static ul_clock_type master_snoc_cnoc_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_snoc_cnoc =
{
  /* Master Data */
  "/icb/master/snoc_cnoc",
  ICBID_MASTER_SNOC_CNOC,                   /* External Master ID */
  8,
  1,
  master_snoc_cnoc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_snoc_cnoc,
    NULL,
  },
  &cfg_master_snoc_cnoc,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_snoc_cnoc,
    NULL,
  },
};

/* Slaves */
/* PMIC_ARB */
static ul_clock_type slave_pmic_arb_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_pmic_arb =
{
  /* Slave Data */
  "/icb/slave/pmic_arb",
  ICBID_SLAVE_PMIC_ARB,                    /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_pmic_arb_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_pmic_arb,
    NULL,
  },
  &cfg_slave_pmic_arb
};

/* TLMM_NORTH */
static ul_clock_type slave_tlmm_north_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_tlmm_north =
{
  /* Slave Data */
  "/icb/slave/tlmm_north",
  ICBID_SLAVE_TLMM_NORTH,                  /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_tlmm_north_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_tlmm_north,
    NULL,
  },
  &cfg_slave_tlmm_north
};

/* MESSAGE_RAM */
static ul_clock_type slave_message_ram_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_message_ram =
{
  /* Slave Data */
  "/icb/slave/message_ram",
  ICBID_SLAVE_MESSAGE_RAM,                 /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_message_ram_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_message_ram,
    NULL,
  },
  &cfg_slave_message_ram
};

/* PRNG */
static ul_clock_type slave_prng_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_prng =
{
  /* Slave Data */
  "/icb/slave/prng",
  ICBID_SLAVE_PRNG,                        /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_prng_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_prng,
    NULL,
  },
  &cfg_slave_prng
};

/* TCSR */
static ul_clock_type slave_tcsr_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_tcsr =
{
  /* Slave Data */
  "/icb/slave/tcsr",
  ICBID_SLAVE_TCSR,                        /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_tcsr_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_tcsr,
    NULL,
  },
  &cfg_slave_tcsr
};

/* SNOC_CFG */
static ul_clock_type slave_snoc_cfg_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_snoc_cfg =
{
  /* Slave Data */
  "/icb/slave/snoc_cfg",
  ICBID_SLAVE_SNOC_CFG,                    /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_snoc_cfg_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_snoc_cfg,
    NULL,
  },
  &cfg_slave_snoc_cfg
};

/* CLK_CTL */
static ul_clock_type slave_clk_ctl_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_clk_ctl =
{
  /* Slave Data */
  "/icb/slave/clk_ctl",
  ICBID_SLAVE_CLK_CTL,                     /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_clk_ctl_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_clk_ctl,
    NULL,
  },
  &cfg_slave_clk_ctl
};

/* GLM */
static ul_clock_type slave_glm_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_glm =
{
  /* Slave Data */
  "/icb/slave/glm",
  ICBID_SLAVE_GLM,                         /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_glm_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_glm,
    NULL,
  },
  &cfg_slave_glm
};

/* MSS_CFG */
static ul_clock_type slave_mss_cfg_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_mss_cfg =
{
  /* Slave Data */
  "/icb/slave/mss_cfg",
  ICBID_SLAVE_CNOC_MSS,                    /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_mss_cfg_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_mss_cfg,
    NULL,
  },
  &cfg_slave_mss_cfg
};

/* TLMM_WEST */
static ul_clock_type slave_tlmm_west_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_tlmm_west =
{
  /* Slave Data */
  "/icb/slave/tlmm_west",
  ICBID_SLAVE_TLMM_WEST,                   /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_tlmm_west_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_tlmm_west,
    NULL,
  },
  &cfg_slave_tlmm_west
};

/* BLSP_2 */
static ul_clock_type slave_blsp_2_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_blsp_2 =
{
  /* Slave Data */
  "/icb/slave/blsp_2",
  ICBID_SLAVE_BLSP_2,                      /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_blsp_2_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_blsp_2,
    NULL,
  },
  &cfg_slave_blsp_2
};

/* PDM */
static ul_clock_type slave_pdm_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_pdm =
{
  /* Slave Data */
  "/icb/slave/pdm",
  ICBID_SLAVE_PDM,                         /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_pdm_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_pdm,
    NULL,
  },
  &cfg_slave_pdm
};

/* BLSP_1 */
static ul_clock_type slave_blsp_1_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_blsp_1 =
{
  /* Slave Data */
  "/icb/slave/blsp_1",
  ICBID_SLAVE_BLSP_1,                      /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_blsp_1_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_blsp_1,
    NULL,
  },
  &cfg_slave_blsp_1
};

/* SDCC_2 */
static ul_clock_type slave_sdcc_2_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_sdcc_2 =
{
  /* Slave Data */
  "/icb/slave/sdcc_2",
  ICBID_SLAVE_SDCC_2,                      /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_sdcc_2_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_sdcc_2,
    NULL,
  },
  &cfg_slave_sdcc_2
};

/* SDCC_4 */
static ul_clock_type slave_sdcc_4_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_sdcc_4 =
{
  /* Slave Data */
  "/icb/slave/sdcc_4",
  ICBID_SLAVE_SDCC_4,                      /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_sdcc_4_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_sdcc_4,
    NULL,
  },
  &cfg_slave_sdcc_4
};

/* TLMM_EAST */
static ul_clock_type slave_tlmm_east_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_tlmm_east =
{
  /* Slave Data */
  "/icb/slave/tlmm_east",
  ICBID_SLAVE_TLMM_EAST,                   /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_tlmm_east_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_tlmm_east,
    NULL,
  },
  &cfg_slave_tlmm_east
};

/*****************************************************/
/*                       cr_virt                                      */
/*****************************************************/
/* Masters */
/* Slaves */
/*****************************************************/
/*                       snoc                                      */
/*****************************************************/
/* Masters */
/* LPASS_AHB */
static ul_clock_type master_lpass_ahb_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_lpass_ahb =
{
  /* Master Data */
  "/icb/master/lpass_ahb",
  ICBID_MASTER_LPASS_AHB,                   /* External Master ID */
  16,
  1,
  master_lpass_ahb_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_lpass_ahb,
    NULL,
  },
  &cfg_master_lpass_ahb,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_lpass_ahb,
    NULL,
  },
};

/* SNOC_CFG */
static ul_clock_type master_snoc_cfg_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_snoc_cfg =
{
  /* Master Data */
  "/icb/master/snoc_cfg",
  ICBID_MASTER_SNOC_CFG,                    /* External Master ID */
  16,
  1,
  master_snoc_cfg_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_snoc_cfg,
    NULL,
  },
  &cfg_master_snoc_cfg,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_snoc_cfg,
    NULL,
  },
};

/* A1NOC_SNOC */
static ul_clock_type master_a1noc_snoc_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_a1noc_snoc =
{
  /* Master Data */
  "/icb/master/a1noc_snoc",
  ICBID_MASTER_A1NOC_SNOC,                  /* External Master ID */
  16,
  1,
  master_a1noc_snoc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_a1noc_snoc,
    NULL,
  },
  &cfg_master_a1noc_snoc,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_a1noc_snoc,
    NULL,
  },
};

/* LPASS_PROC */
static ul_clock_type master_lpass_proc_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_lpass_proc =
{
  /* Master Data */
  "/icb/master/lpass_proc",
  ICBID_MASTER_LPASS_PROC,                  /* External Master ID */
  32,
  1,
  master_lpass_proc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_lpass_proc,
    NULL,
  },
  &cfg_master_lpass_proc,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_lpass_proc,
    NULL,
  },
};

/* Slaves */
/* SNOC_BIMC */
static ul_clock_type slave_snoc_bimc_slv_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_snoc_bimc =
{
  /* Slave Data */
  "/icb/slave/snoc_bimc",
  ICBID_SLAVE_SNOC_BIMC,                   /* External Slave ID */
  32,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_snoc_bimc_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_snoc_bimc,
    NULL,
  },
  &cfg_slave_snoc_bimc
};

/* SNOC_CNOC */
static ul_clock_type slave_snoc_cnoc_slv_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_snoc_cnoc =
{
  /* Slave Data */
  "/icb/slave/snoc_cnoc",
  ICBID_SLAVE_SNOC_CNOC,                   /* External Slave ID */
  16,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_snoc_cnoc_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_snoc_cnoc,
    NULL,
  },
  &cfg_slave_snoc_cnoc
};

/* IMEM */
static ul_clock_type slave_imem_slv_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_imem =
{
  /* Slave Data */
  "/icb/slave/imem",
  ICBID_SLAVE_IMEM,                        /* External Slave ID */
  16,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_imem_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_imem,
    NULL,
  },
  &cfg_slave_imem
};

/* PIMEM */
static ul_clock_type slave_pimem_slv_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_pimem =
{
  /* Slave Data */
  "/icb/slave/pimem",
  ICBID_SLAVE_PIMEM,                       /* External Slave ID */
  16,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_pimem_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_pimem,
    NULL,
  },
  &cfg_slave_pimem
};

/* QDSS_STM */
static ul_clock_type slave_qdss_stm_slv_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_qdss_stm =
{
  /* Slave Data */
  "/icb/slave/qdss_stm",
  ICBID_SLAVE_QDSS_STM,                    /* External Slave ID */
  16,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_qdss_stm_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_qdss_stm,
    NULL,
  },
  &cfg_slave_qdss_stm
};

/* SRVC_SNOC */
static ul_clock_type slave_srvc_snoc_slv_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_srvc_snoc =
{
  /* Slave Data */
  "/icb/slave/srvc_snoc",
  ICBID_SLAVE_SERVICE_SNOC,                /* External Slave ID */
  16,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_srvc_snoc_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_srvc_snoc,
    NULL,
  },
  &cfg_slave_srvc_snoc
};

/* Define the valid routes  */
static ul_pair_type route_blsp_2_ebi_list_array[3] =
{
  {
    &master_blsp_2,
    &slave_a1noc_snoc
  },
  {
    &master_a1noc_snoc,
    &slave_snoc_bimc
  },
  {
    &master_snoc_bimc,
    &slave_ebi
  },
};
static ul_route_list_type route_blsp_2_ebi_list =
{
  3,
  route_blsp_2_ebi_list_array
};
static ul_pair_type route_blsp_2_hmss_l3_list_array[3] =
{
  {
    &master_blsp_2,
    &slave_a1noc_snoc
  },
  {
    &master_a1noc_snoc,
    &slave_snoc_bimc
  },
  {
    &master_snoc_bimc,
    &slave_hmss_l3
  },
};
static ul_route_list_type route_blsp_2_hmss_l3_list =
{
  3,
  route_blsp_2_hmss_l3_list_array
};
static ul_pair_type route_blsp_2_imem_list_array[2] =
{
  {
    &master_blsp_2,
    &slave_a1noc_snoc
  },
  {
    &master_a1noc_snoc,
    &slave_imem
  },
};
static ul_route_list_type route_blsp_2_imem_list =
{
  2,
  route_blsp_2_imem_list_array
};
static ul_pair_type route_blsp_2_pimem_list_array[2] =
{
  {
    &master_blsp_2,
    &slave_a1noc_snoc
  },
  {
    &master_a1noc_snoc,
    &slave_pimem
  },
};
static ul_route_list_type route_blsp_2_pimem_list =
{
  2,
  route_blsp_2_pimem_list_array
};
static ul_pair_type route_blsp_2_qdss_stm_list_array[2] =
{
  {
    &master_blsp_2,
    &slave_a1noc_snoc
  },
  {
    &master_a1noc_snoc,
    &slave_qdss_stm
  },
};
static ul_route_list_type route_blsp_2_qdss_stm_list =
{
  2,
  route_blsp_2_qdss_stm_list_array
};
static ul_pair_type route_lpass_ahb_blsp_1_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_blsp_1
  },
};
static ul_route_list_type route_lpass_ahb_blsp_1_list =
{
  2,
  route_lpass_ahb_blsp_1_list_array
};
static ul_pair_type route_lpass_ahb_blsp_2_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_blsp_2
  },
};
static ul_route_list_type route_lpass_ahb_blsp_2_list =
{
  2,
  route_lpass_ahb_blsp_2_list_array
};
static ul_pair_type route_lpass_ahb_clk_ctl_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_clk_ctl
  },
};
static ul_route_list_type route_lpass_ahb_clk_ctl_list =
{
  2,
  route_lpass_ahb_clk_ctl_list_array
};
static ul_pair_type route_lpass_ahb_ebi_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_bimc
  },
  {
    &master_snoc_bimc,
    &slave_ebi
  },
};
static ul_route_list_type route_lpass_ahb_ebi_list =
{
  2,
  route_lpass_ahb_ebi_list_array
};
static ul_pair_type route_lpass_ahb_glm_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_glm
  },
};
static ul_route_list_type route_lpass_ahb_glm_list =
{
  2,
  route_lpass_ahb_glm_list_array
};
static ul_pair_type route_lpass_ahb_hmss_l3_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_bimc
  },
  {
    &master_snoc_bimc,
    &slave_hmss_l3
  },
};
static ul_route_list_type route_lpass_ahb_hmss_l3_list =
{
  2,
  route_lpass_ahb_hmss_l3_list_array
};
static ul_pair_type route_lpass_ahb_imem_list_array[1] =
{
  {
    &master_lpass_ahb,
    &slave_imem
  },
};
static ul_route_list_type route_lpass_ahb_imem_list =
{
  1,
  route_lpass_ahb_imem_list_array
};
static ul_pair_type route_lpass_ahb_message_ram_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_message_ram
  },
};
static ul_route_list_type route_lpass_ahb_message_ram_list =
{
  2,
  route_lpass_ahb_message_ram_list_array
};
static ul_pair_type route_lpass_ahb_mss_cfg_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_mss_cfg
  },
};
static ul_route_list_type route_lpass_ahb_mss_cfg_list =
{
  2,
  route_lpass_ahb_mss_cfg_list_array
};
static ul_pair_type route_lpass_ahb_pdm_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_pdm
  },
};
static ul_route_list_type route_lpass_ahb_pdm_list =
{
  2,
  route_lpass_ahb_pdm_list_array
};
static ul_pair_type route_lpass_ahb_pimem_list_array[1] =
{
  {
    &master_lpass_ahb,
    &slave_pimem
  },
};
static ul_route_list_type route_lpass_ahb_pimem_list =
{
  1,
  route_lpass_ahb_pimem_list_array
};
static ul_pair_type route_lpass_ahb_pmic_arb_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_pmic_arb
  },
};
static ul_route_list_type route_lpass_ahb_pmic_arb_list =
{
  2,
  route_lpass_ahb_pmic_arb_list_array
};
static ul_pair_type route_lpass_ahb_prng_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_prng
  },
};
static ul_route_list_type route_lpass_ahb_prng_list =
{
  2,
  route_lpass_ahb_prng_list_array
};
static ul_pair_type route_lpass_ahb_sdcc_2_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_sdcc_2
  },
};
static ul_route_list_type route_lpass_ahb_sdcc_2_list =
{
  2,
  route_lpass_ahb_sdcc_2_list_array
};
static ul_pair_type route_lpass_ahb_sdcc_4_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_sdcc_4
  },
};
static ul_route_list_type route_lpass_ahb_sdcc_4_list =
{
  2,
  route_lpass_ahb_sdcc_4_list_array
};
static ul_pair_type route_lpass_ahb_snoc_cfg_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_snoc_cfg
  },
};
static ul_route_list_type route_lpass_ahb_snoc_cfg_list =
{
  2,
  route_lpass_ahb_snoc_cfg_list_array
};
static ul_pair_type route_lpass_ahb_tcsr_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_tcsr
  },
};
static ul_route_list_type route_lpass_ahb_tcsr_list =
{
  2,
  route_lpass_ahb_tcsr_list_array
};
static ul_pair_type route_lpass_ahb_tlmm_east_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_tlmm_east
  },
};
static ul_route_list_type route_lpass_ahb_tlmm_east_list =
{
  2,
  route_lpass_ahb_tlmm_east_list_array
};
static ul_pair_type route_lpass_ahb_tlmm_north_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_tlmm_north
  },
};
static ul_route_list_type route_lpass_ahb_tlmm_north_list =
{
  2,
  route_lpass_ahb_tlmm_north_list_array
};
static ul_pair_type route_lpass_ahb_tlmm_west_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_tlmm_west
  },
};
static ul_route_list_type route_lpass_ahb_tlmm_west_list =
{
  2,
  route_lpass_ahb_tlmm_west_list_array
};
static ul_pair_type route_lpass_proc_blsp_1_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_blsp_1
  },
};
static ul_route_list_type route_lpass_proc_blsp_1_list =
{
  2,
  route_lpass_proc_blsp_1_list_array
};
static ul_pair_type route_lpass_proc_blsp_2_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_blsp_2
  },
};
static ul_route_list_type route_lpass_proc_blsp_2_list =
{
  2,
  route_lpass_proc_blsp_2_list_array
};
static ul_pair_type route_lpass_proc_clk_ctl_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_clk_ctl
  },
};
static ul_route_list_type route_lpass_proc_clk_ctl_list =
{
  2,
  route_lpass_proc_clk_ctl_list_array
};
static ul_pair_type route_lpass_proc_ebi_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_snoc_bimc
  },
  {
    &master_snoc_bimc,
    &slave_ebi
  },
};
static ul_route_list_type route_lpass_proc_ebi_list =
{
  2,
  route_lpass_proc_ebi_list_array
};
static ul_pair_type route_lpass_proc_glm_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_glm
  },
};
static ul_route_list_type route_lpass_proc_glm_list =
{
  2,
  route_lpass_proc_glm_list_array
};
static ul_pair_type route_lpass_proc_hmss_l3_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_snoc_bimc
  },
  {
    &master_snoc_bimc,
    &slave_hmss_l3
  },
};
static ul_route_list_type route_lpass_proc_hmss_l3_list =
{
  2,
  route_lpass_proc_hmss_l3_list_array
};
static ul_pair_type route_lpass_proc_imem_list_array[1] =
{
  {
    &master_lpass_proc,
    &slave_imem
  },
};
static ul_route_list_type route_lpass_proc_imem_list =
{
  1,
  route_lpass_proc_imem_list_array
};
static ul_pair_type route_lpass_proc_message_ram_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_message_ram
  },
};
static ul_route_list_type route_lpass_proc_message_ram_list =
{
  2,
  route_lpass_proc_message_ram_list_array
};
static ul_pair_type route_lpass_proc_mss_cfg_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_mss_cfg
  },
};
static ul_route_list_type route_lpass_proc_mss_cfg_list =
{
  2,
  route_lpass_proc_mss_cfg_list_array
};
static ul_pair_type route_lpass_proc_pdm_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_pdm
  },
};
static ul_route_list_type route_lpass_proc_pdm_list =
{
  2,
  route_lpass_proc_pdm_list_array
};
static ul_pair_type route_lpass_proc_pimem_list_array[1] =
{
  {
    &master_lpass_proc,
    &slave_pimem
  },
};
static ul_route_list_type route_lpass_proc_pimem_list =
{
  1,
  route_lpass_proc_pimem_list_array
};
static ul_pair_type route_lpass_proc_pmic_arb_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_pmic_arb
  },
};
static ul_route_list_type route_lpass_proc_pmic_arb_list =
{
  2,
  route_lpass_proc_pmic_arb_list_array
};
static ul_pair_type route_lpass_proc_prng_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_prng
  },
};
static ul_route_list_type route_lpass_proc_prng_list =
{
  2,
  route_lpass_proc_prng_list_array
};
static ul_pair_type route_lpass_proc_qdss_stm_list_array[1] =
{
  {
    &master_lpass_proc,
    &slave_qdss_stm
  },
};
static ul_route_list_type route_lpass_proc_qdss_stm_list =
{
  1,
  route_lpass_proc_qdss_stm_list_array
};
static ul_pair_type route_lpass_proc_sdcc_2_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_sdcc_2
  },
};
static ul_route_list_type route_lpass_proc_sdcc_2_list =
{
  2,
  route_lpass_proc_sdcc_2_list_array
};
static ul_pair_type route_lpass_proc_sdcc_4_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_sdcc_4
  },
};
static ul_route_list_type route_lpass_proc_sdcc_4_list =
{
  2,
  route_lpass_proc_sdcc_4_list_array
};
static ul_pair_type route_lpass_proc_snoc_cfg_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_snoc_cfg
  },
};
static ul_route_list_type route_lpass_proc_snoc_cfg_list =
{
  2,
  route_lpass_proc_snoc_cfg_list_array
};
static ul_pair_type route_lpass_proc_tcsr_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_tcsr
  },
};
static ul_route_list_type route_lpass_proc_tcsr_list =
{
  2,
  route_lpass_proc_tcsr_list_array
};
static ul_pair_type route_lpass_proc_tlmm_east_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_tlmm_east
  },
};
static ul_route_list_type route_lpass_proc_tlmm_east_list =
{
  2,
  route_lpass_proc_tlmm_east_list_array
};
static ul_pair_type route_lpass_proc_tlmm_north_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_tlmm_north
  },
};
static ul_route_list_type route_lpass_proc_tlmm_north_list =
{
  2,
  route_lpass_proc_tlmm_north_list_array
};
static ul_pair_type route_lpass_proc_tlmm_west_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_tlmm_west
  },
};
static ul_route_list_type route_lpass_proc_tlmm_west_list =
{
  2,
  route_lpass_proc_tlmm_west_list_array
};
static ul_pair_type route_snoc_cfg_srvc_snoc_list_array[1] =
{
  {
    &master_snoc_cfg,
    &slave_srvc_snoc
  },
};
static ul_route_list_type route_snoc_cfg_srvc_snoc_list =
{
  1,
  route_snoc_cfg_srvc_snoc_list_array
};

/*============================================================================
                         ROUTE TREE - 47 routes
============================================================================*/
/* Forward declarations */
static ul_treeNodeType route_0x1200000000L_lpass_ahb_ebi_node;
static ul_treeNodeType route_0x120000001aL_lpass_ahb_imem_node;
static ul_treeNodeType route_0x1200000021L_lpass_ahb_sdcc_2_node;
static ul_treeNodeType route_0x1200000022L_lpass_ahb_sdcc_4_node;
static ul_treeNodeType route_0x1200000025L_lpass_ahb_blsp_2_node;
static ul_treeNodeType route_0x1200000027L_lpass_ahb_blsp_1_node;
static ul_treeNodeType route_0x1200000029L_lpass_ahb_pdm_node;
static ul_treeNodeType route_0x120000002cL_lpass_ahb_prng_node;
static ul_treeNodeType route_0x120000002fL_lpass_ahb_clk_ctl_node;
static ul_treeNodeType route_0x1200000030L_lpass_ahb_mss_cfg_node;
static ul_treeNodeType route_0x1200000032L_lpass_ahb_tcsr_node;
static ul_treeNodeType route_0x1200000037L_lpass_ahb_message_ram_node;
static ul_treeNodeType route_0x120000003bL_lpass_ahb_pmic_arb_node;
static ul_treeNodeType route_0x1200000046L_lpass_ahb_snoc_cfg_node;
static ul_treeNodeType route_0x12000000a0L_lpass_ahb_hmss_l3_node;
static ul_treeNodeType route_0x12000000a6L_lpass_ahb_pimem_node;
static ul_treeNodeType route_0x12000000d1L_lpass_ahb_glm_node;
static ul_treeNodeType route_0x12000000d5L_lpass_ahb_tlmm_east_node;
static ul_treeNodeType route_0x12000000d6L_lpass_ahb_tlmm_north_node;
static ul_treeNodeType route_0x12000000d7L_lpass_ahb_tlmm_west_node;
static ul_treeNodeType route_0x140000001dL_snoc_cfg_srvc_snoc_node;
static ul_treeNodeType route_0x1900000000L_lpass_proc_ebi_node;
static ul_treeNodeType route_0x190000001aL_lpass_proc_imem_node;
static ul_treeNodeType route_0x190000001eL_lpass_proc_qdss_stm_node;
static ul_treeNodeType route_0x1900000021L_lpass_proc_sdcc_2_node;
static ul_treeNodeType route_0x1900000022L_lpass_proc_sdcc_4_node;
static ul_treeNodeType route_0x1900000025L_lpass_proc_blsp_2_node;
static ul_treeNodeType route_0x1900000027L_lpass_proc_blsp_1_node;
static ul_treeNodeType route_0x1900000029L_lpass_proc_pdm_node;
static ul_treeNodeType route_0x190000002cL_lpass_proc_prng_node;
static ul_treeNodeType route_0x190000002fL_lpass_proc_clk_ctl_node;
static ul_treeNodeType route_0x1900000030L_lpass_proc_mss_cfg_node;
static ul_treeNodeType route_0x1900000032L_lpass_proc_tcsr_node;
static ul_treeNodeType route_0x1900000037L_lpass_proc_message_ram_node;
static ul_treeNodeType route_0x190000003bL_lpass_proc_pmic_arb_node;
static ul_treeNodeType route_0x1900000046L_lpass_proc_snoc_cfg_node;
static ul_treeNodeType route_0x19000000a0L_lpass_proc_hmss_l3_node;
static ul_treeNodeType route_0x19000000a6L_lpass_proc_pimem_node;
static ul_treeNodeType route_0x19000000d1L_lpass_proc_glm_node;
static ul_treeNodeType route_0x19000000d5L_lpass_proc_tlmm_east_node;
static ul_treeNodeType route_0x19000000d6L_lpass_proc_tlmm_north_node;
static ul_treeNodeType route_0x19000000d7L_lpass_proc_tlmm_west_node;
static ul_treeNodeType route_0x2700000000L_blsp_2_ebi_node;
static ul_treeNodeType route_0x270000001aL_blsp_2_imem_node;
static ul_treeNodeType route_0x270000001eL_blsp_2_qdss_stm_node;
static ul_treeNodeType route_0x27000000a0L_blsp_2_hmss_l3_node;
static ul_treeNodeType route_0x27000000a6L_blsp_2_pimem_node;

/* Create the tree */
static ul_treeNodeType route_0x1200000000L_lpass_ahb_ebi_node =
{
  0x1200000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_ebi_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x120000001aL_lpass_ahb_imem_node =
{
  0x120000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_imem_list,
  &route_0x1200000000L_lpass_ahb_ebi_node,
  &route_0x1200000021L_lpass_ahb_sdcc_2_node
};
static ul_treeNodeType route_0x1200000021L_lpass_ahb_sdcc_2_node =
{
  0x1200000021ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_sdcc_2_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1200000022L_lpass_ahb_sdcc_4_node =
{
  0x1200000022ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_sdcc_4_list,
  &route_0x120000001aL_lpass_ahb_imem_node,
  &route_0x1200000027L_lpass_ahb_blsp_1_node
};
static ul_treeNodeType route_0x1200000025L_lpass_ahb_blsp_2_node =
{
  0x1200000025ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_blsp_2_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1200000027L_lpass_ahb_blsp_1_node =
{
  0x1200000027ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_blsp_1_list,
  &route_0x1200000025L_lpass_ahb_blsp_2_node,
  &route_0x1200000029L_lpass_ahb_pdm_node
};
static ul_treeNodeType route_0x1200000029L_lpass_ahb_pdm_node =
{
  0x1200000029ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_pdm_list,
  NULL,
  &route_0x120000002cL_lpass_ahb_prng_node
};
static ul_treeNodeType route_0x120000002cL_lpass_ahb_prng_node =
{
  0x120000002cULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_prng_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x120000002fL_lpass_ahb_clk_ctl_node =
{
  0x120000002fULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_clk_ctl_list,
  &route_0x1200000022L_lpass_ahb_sdcc_4_node,
  &route_0x12000000a0L_lpass_ahb_hmss_l3_node
};
static ul_treeNodeType route_0x1200000030L_lpass_ahb_mss_cfg_node =
{
  0x1200000030ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_mss_cfg_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1200000032L_lpass_ahb_tcsr_node =
{
  0x1200000032ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_tcsr_list,
  &route_0x1200000030L_lpass_ahb_mss_cfg_node,
  &route_0x120000003bL_lpass_ahb_pmic_arb_node
};
static ul_treeNodeType route_0x1200000037L_lpass_ahb_message_ram_node =
{
  0x1200000037ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_message_ram_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x120000003bL_lpass_ahb_pmic_arb_node =
{
  0x120000003bULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_pmic_arb_list,
  &route_0x1200000037L_lpass_ahb_message_ram_node,
  &route_0x1200000046L_lpass_ahb_snoc_cfg_node
};
static ul_treeNodeType route_0x1200000046L_lpass_ahb_snoc_cfg_node =
{
  0x1200000046ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_snoc_cfg_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x12000000a0L_lpass_ahb_hmss_l3_node =
{
  0x12000000a0ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_hmss_l3_list,
  &route_0x1200000032L_lpass_ahb_tcsr_node,
  &route_0x12000000d5L_lpass_ahb_tlmm_east_node
};
static ul_treeNodeType route_0x12000000a6L_lpass_ahb_pimem_node =
{
  0x12000000a6ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_pimem_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x12000000d1L_lpass_ahb_glm_node =
{
  0x12000000d1ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_glm_list,
  &route_0x12000000a6L_lpass_ahb_pimem_node,
  NULL
};
static ul_treeNodeType route_0x12000000d5L_lpass_ahb_tlmm_east_node =
{
  0x12000000d5ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_tlmm_east_list,
  &route_0x12000000d1L_lpass_ahb_glm_node,
  &route_0x140000001dL_snoc_cfg_srvc_snoc_node
};
static ul_treeNodeType route_0x12000000d6L_lpass_ahb_tlmm_north_node =
{
  0x12000000d6ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_tlmm_north_list,
  NULL,
  &route_0x12000000d7L_lpass_ahb_tlmm_west_node
};
static ul_treeNodeType route_0x12000000d7L_lpass_ahb_tlmm_west_node =
{
  0x12000000d7ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_tlmm_west_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x140000001dL_snoc_cfg_srvc_snoc_node =
{
  0x140000001dULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_snoc_cfg_srvc_snoc_list,
  &route_0x12000000d6L_lpass_ahb_tlmm_north_node,
  &route_0x1900000000L_lpass_proc_ebi_node
};
static ul_treeNodeType route_0x1900000000L_lpass_proc_ebi_node =
{
  0x1900000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_ebi_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x190000001aL_lpass_proc_imem_node =
{
  0x190000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_imem_list,
  &route_0x120000002fL_lpass_ahb_clk_ctl_node,
  &route_0x19000000a6L_lpass_proc_pimem_node
};
static ul_treeNodeType route_0x190000001eL_lpass_proc_qdss_stm_node =
{
  0x190000001eULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_qdss_stm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1900000021L_lpass_proc_sdcc_2_node =
{
  0x1900000021ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_sdcc_2_list,
  &route_0x190000001eL_lpass_proc_qdss_stm_node,
  NULL
};
static ul_treeNodeType route_0x1900000022L_lpass_proc_sdcc_4_node =
{
  0x1900000022ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_sdcc_4_list,
  &route_0x1900000021L_lpass_proc_sdcc_2_node,
  &route_0x1900000027L_lpass_proc_blsp_1_node
};
static ul_treeNodeType route_0x1900000025L_lpass_proc_blsp_2_node =
{
  0x1900000025ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_blsp_2_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1900000027L_lpass_proc_blsp_1_node =
{
  0x1900000027ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_blsp_1_list,
  &route_0x1900000025L_lpass_proc_blsp_2_node,
  &route_0x1900000029L_lpass_proc_pdm_node
};
static ul_treeNodeType route_0x1900000029L_lpass_proc_pdm_node =
{
  0x1900000029ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_pdm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x190000002cL_lpass_proc_prng_node =
{
  0x190000002cULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_prng_list,
  &route_0x1900000022L_lpass_proc_sdcc_4_node,
  &route_0x1900000037L_lpass_proc_message_ram_node
};
static ul_treeNodeType route_0x190000002fL_lpass_proc_clk_ctl_node =
{
  0x190000002fULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_clk_ctl_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1900000030L_lpass_proc_mss_cfg_node =
{
  0x1900000030ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_mss_cfg_list,
  &route_0x190000002fL_lpass_proc_clk_ctl_node,
  &route_0x1900000032L_lpass_proc_tcsr_node
};
static ul_treeNodeType route_0x1900000032L_lpass_proc_tcsr_node =
{
  0x1900000032ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_tcsr_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1900000037L_lpass_proc_message_ram_node =
{
  0x1900000037ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_message_ram_list,
  &route_0x1900000030L_lpass_proc_mss_cfg_node,
  &route_0x1900000046L_lpass_proc_snoc_cfg_node
};
static ul_treeNodeType route_0x190000003bL_lpass_proc_pmic_arb_node =
{
  0x190000003bULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_pmic_arb_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1900000046L_lpass_proc_snoc_cfg_node =
{
  0x1900000046ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_snoc_cfg_list,
  &route_0x190000003bL_lpass_proc_pmic_arb_node,
  &route_0x19000000a0L_lpass_proc_hmss_l3_node
};
static ul_treeNodeType route_0x19000000a0L_lpass_proc_hmss_l3_node =
{
  0x19000000a0ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_hmss_l3_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x19000000a6L_lpass_proc_pimem_node =
{
  0x19000000a6ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_pimem_list,
  &route_0x190000002cL_lpass_proc_prng_node,
  &route_0x270000001aL_blsp_2_imem_node
};
static ul_treeNodeType route_0x19000000d1L_lpass_proc_glm_node =
{
  0x19000000d1ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_glm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x19000000d5L_lpass_proc_tlmm_east_node =
{
  0x19000000d5ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_tlmm_east_list,
  &route_0x19000000d1L_lpass_proc_glm_node,
  &route_0x19000000d7L_lpass_proc_tlmm_west_node
};
static ul_treeNodeType route_0x19000000d6L_lpass_proc_tlmm_north_node =
{
  0x19000000d6ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_tlmm_north_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x19000000d7L_lpass_proc_tlmm_west_node =
{
  0x19000000d7ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_tlmm_west_list,
  &route_0x19000000d6L_lpass_proc_tlmm_north_node,
  &route_0x2700000000L_blsp_2_ebi_node
};
static ul_treeNodeType route_0x2700000000L_blsp_2_ebi_node =
{
  0x2700000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_blsp_2_ebi_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x270000001aL_blsp_2_imem_node =
{
  0x270000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_blsp_2_imem_list,
  &route_0x19000000d5L_lpass_proc_tlmm_east_node,
  &route_0x27000000a0L_blsp_2_hmss_l3_node
};
static ul_treeNodeType route_0x270000001eL_blsp_2_qdss_stm_node =
{
  0x270000001eULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_blsp_2_qdss_stm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x27000000a0L_blsp_2_hmss_l3_node =
{
  0x27000000a0ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_blsp_2_hmss_l3_list,
  &route_0x270000001eL_blsp_2_qdss_stm_node,
  &route_0x27000000a6L_blsp_2_pimem_node
};
static ul_treeNodeType route_0x27000000a6L_blsp_2_pimem_node =
{
  0x27000000a6ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_blsp_2_pimem_list,
  NULL,
  NULL
};

/*============================================================================
                   EXTERNAL DATA DECLARATIONS
============================================================================*/
/* Pointer to the root node */
ul_treeNodeType * route_tree_root = 
  &route_0x190000001aL_lpass_proc_imem_node;

const uint32 u32ul_arb_master_list_size   = 7;
ul_master_data_type *ul_arb_master_list[] =
{
  &master_a1noc_snoc,
  &master_blsp_2,
  &master_lpass_ahb,
  &master_lpass_proc,
  &master_snoc_bimc,
  &master_snoc_cfg,
  &master_snoc_cnoc,
};

const uint32 u32ul_arb_slave_list_size   = 25;
ul_slave_data_type *ul_arb_slave_list[] =
{
  &slave_a1noc_snoc,
  &slave_blsp_1,
  &slave_blsp_2,
  &slave_clk_ctl,
  &slave_ebi,
  &slave_glm,
  &slave_hmss_l3,
  &slave_imem,
  &slave_message_ram,
  &slave_mss_cfg,
  &slave_pdm,
  &slave_pimem,
  &slave_pmic_arb,
  &slave_prng,
  &slave_qdss_stm,
  &slave_sdcc_2,
  &slave_sdcc_4,
  &slave_snoc_bimc,
  &slave_snoc_cfg,
  &slave_snoc_cnoc,
  &slave_srvc_snoc,
  &slave_tcsr,
  &slave_tlmm_east,
  &slave_tlmm_north,
  &slave_tlmm_west,
};

/* Have to make the array size a const so we can export it */
const uint32 u32ul_arb_clk_node_list_size   = 4;
const char *ul_arb_clock_node_list[] =
{
  "/clk/agr1",
  "/clk/bimc",
  "/clk/cnoc",
  "/clk/snoc",
};

