#ifndef __COEMFIDOCONFIG_H
#define __COEMFIDOCONFIG_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

// This class provides the configuration blob for the fidocrypto application.

// It implements the `ISource` interface.

//

#define COEMFidoConfig_UID UINT32_C(1025)

#endif /* __COEMFIDOCONFIG_H */
