#ifndef PGS_SERVICE_01_H
#define PGS_SERVICE_01_H
/**
  @file adsp_lpm_voting_v01.h

  @brief This is the public header file which defines the pgs service Data structures.

  This header file defines the types and structures that were defined in
  pgs. It contains the constant values defined, enums, structures,
  messages, and service message IDs (in that order) Structures that were
  defined in the IDL as messages contain mandatory elements, optional
  elements, a combination of mandatory and optional elements (mandatory
  always come before optionals in the structure), or nothing (null message)

  An optional element in a message is preceded by a uint8_t value that must be
  set to true if the element is going to be included. When decoding a received
  message, the uint8_t values will be set to true or false by the decode
  routine, and should be checked before accessing the values that they
  correspond to.

  Variable sized arrays are defined as static sized arrays with an unsigned
  integer (32 bit) preceding it that must be set to the number of elements
  in the array that are valid. For Example:

  uint32_t test_opaque_len;
  uint8_t test_opaque[16];

  If only 4 elements are added to test_opaque[] then test_opaque_len must be
  set to 4 before sending the message.  When decoding, the _len value is set
  by the decode routine and should be checked so that the correct number of
  elements in the array will be accessed.

*/
/*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*
  Copyright (c) 2019 Qualcomm Technologies, Inc.
 All rights reserved.
 Confidential and Proprietary - Qualcomm Technologies, Inc.


  $Header: //components/rel/qmimsgs.adsp/2.6/adsp_lpm_voting/api/adsp_lpm_voting_v01.h#1 $
 *====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*/
/*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*
 *THIS IS AN AUTO GENERATED FILE. DO NOT ALTER IN ANY WAY
 *====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*/

/* This file was generated with Tool version 6.14.9 
   It was generated on: Fri Sep 20 2019 (Spin 0)
   From IDL File: adsp_lpm_voting_v01.idl */

/** @defgroup pgs_qmi_consts Constant values defined in the IDL */
/** @defgroup pgs_qmi_msg_ids Constant values for QMI message IDs */
/** @defgroup pgs_qmi_enums Enumerated types used in QMI messages */
/** @defgroup pgs_qmi_messages Structures sent as QMI messages */
/** @defgroup pgs_qmi_aggregates Aggregate types used in QMI messages */
/** @defgroup pgs_qmi_accessor Accessor for QMI service object */
/** @defgroup pgs_qmi_version Constant values for versioning information */

#include <stdint.h>
#include "qmi_idl_lib.h"
#include "common_v01.h"


#ifdef __cplusplus
extern "C" {
#endif

/** @addtogroup pgs_qmi_version
    @{
  */
/** Major Version Number of the IDL used to generate this file */
#define PGS_V01_IDL_MAJOR_VERS 0x01
/** Revision Number of the IDL used to generate this file */
#define PGS_V01_IDL_MINOR_VERS 0x00
/** Major Version Number of the qmi_idl_compiler used to generate this file */
#define PGS_V01_IDL_TOOL_VERS 0x06
/** Maximum Defined Message ID */
#define PGS_V01_MAX_MESSAGE_ID 0x0001
/**
    @}
  */


/** @addtogroup pgs_qmi_consts
    @{
  */
/**
    @}
  */

/** @addtogroup pgs_qmi_messages
    @{
  */
/** Request Message; Sets the LPM vote for HWSOLVER for ADSP */
typedef struct {

  /* Mandatory */
  uint8_t keep_adsp_out_of_lpm;
  /**<   This request allows a client to enable or disable ADSP LPM.
      - TRUE:
        Keep ADSP out of LPM.
      - FALSE:
	    Let ADSP go to LPM mode.
     */
}prod_set_lpm_vote_req_msg_v01;  /* Message */
/**
    @}
  */

/** @addtogroup pgs_qmi_messages
    @{
  */
/** Response Message; Sets the LPM vote for HWSOLVER for ADSP */
typedef struct {

  /* Mandatory */
  /*  Result Code */
  qmi_response_type_v01 resp;
  /**<   Standard response type.*/
}prod_set_lpm_vote_resp_msg_v01;  /* Message */
/**
    @}
  */

/* Conditional compilation tags for message removal */ 
//#define REMOVE_PROD_SET_LPM_VOTE_V01

/*Service Message Definition*/
/** @addtogroup pgs_qmi_msg_ids
    @{
  */
#define PROD_SET_LPM_VOTE_REQ_V01 0x0001
#define PROD_SET_LPM_VOTE_RESP_V01 0x0001
/**
    @}
  */

/* Service Object Accessor */
/** @addtogroup wms_qmi_accessor
    @{
  */
/** This function is used internally by the autogenerated code.  Clients should use the
   macro pgs_get_service_object_v01( ) that takes in no arguments. */
qmi_idl_service_object_type pgs_get_service_object_internal_v01
 ( int32_t idl_maj_version, int32_t idl_min_version, int32_t library_version );

/** This macro should be used to get the service object */
#define pgs_get_service_object_v01( ) \
          pgs_get_service_object_internal_v01( \
            PGS_V01_IDL_MAJOR_VERS, PGS_V01_IDL_MINOR_VERS, \
            PGS_V01_IDL_TOOL_VERS )
/**
    @}
  */


#ifdef __cplusplus
}
#endif
#endif

