#ifndef __CCERTVALIDATE_H
#define __CCERTVALIDATE_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

// This class determines if the provided certificate is valid or not using a set of custom checks

// `IValidate` interface.

//

#define CCertValidate_UID UINT32_C(50)

#endif /* __CCERTVALIDATE_H */
