#ifndef __IVALIDATE_H
#define __IVALIDATE_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define IValidate_ERROR_INVALID INT32_C(10)

#define IValidate_OP_validate 0

static inline int32_t
IValidate_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IValidate_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
IValidate_validate(Object self, const void *data_ptr, size_t data_len)
{
  ObjectArg a[1];
  a[0].bi = (ObjectBufIn) { data_ptr, data_len * 1 };

  return Object_invoke(self, IValidate_OP_validate, a, ObjectCounts_pack(1, 0, 0, 0));
}


#endif /* __IVALIDATE_H */
