#ifndef __UHALTLMMHWIO_H__
#define __UHALTLMMHWIO_H__
/*
===========================================================================
*/
/**
  @file uHALtlmmHWIO.h
  @brief Auto-generated HWIO interface include file.

  Reference chip release:
    SDM660 (Starlord) [starlord_v1.0_p3q3r97_MTO]
 
  This file contains HWIO register definitions for the following modules:
    LPASS_TLMM_GPIO

  'Include' filters applied: 
  'Exclude' filters applied: 
*/
/*
  ===========================================================================

  Copyright (c) 2016 Qualcomm Technologies Incorporated.
  All Rights Reserved.
  Qualcomm Confidential and Proprietary

  Export of this technology or software is regulated by the U.S. Government.
  Diversion contrary to U.S. law prohibited.

  All ideas, data and information contained in or disclosed by
  this document are confidential and proprietary information of
  Qualcomm Technologies Incorporated and all rights therein are expressly reserved.
  By accepting this material the recipient agrees that this material
  and the information contained therein are held in confidence and in
  trust and will not be used, copied, reproduced in whole or in part,
  nor its contents revealed in any manner to others without the express
  written permission of Qualcomm Technologies Incorporated.

  ===========================================================================

  $Header: //components/rel/core.qdsp6/1.0.c2/systemdrivers/tlmm/hw/sdm660/adsp_slpi/uHALtlmmHWIO.h#1 $
  $DateTime: 2020/02/10 01:57:30 $
  $Author: pwbldsvc $

  ===========================================================================
*/

/*----------------------------------------------------------------------------
 * MODULE: LPASS_TLMM_GPIO
 *--------------------------------------------------------------------------*/

#define LPASS_TLMM_GPIO_REG_BASE                                      (LPASS_BASE      + 0x00070000)

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_ADDR                         (LPASS_TLMM_GPIO_REG_BASE      + 0x00000000)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_RMSK                             0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_GPIO_MISC_CFG_BMSK               0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_GPIO_MISC_CFG_SHFT                  0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_GPIO_HIHYS_EN_BMSK                0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_GPIO_HIHYS_EN_SHFT                  0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_GPIO_OE_BMSK                      0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_GPIO_OE_SHFT                        0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_GPIO_HDRIVE_BMSK                  0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_GPIO_HDRIVE_SHFT                    0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_GPIO_FUNC_SEL_BMSK                 0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_GPIO_FUNC_SEL_SHFT                  0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_GPIO_PULL_BMSK                      0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG0_GPIO_PULL_SHFT                      0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT0_ADDR                      (LPASS_TLMM_GPIO_REG_BASE      + 0x00000004)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT0_RMSK                             0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT0_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT0_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT0_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT0_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT0_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT0_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT0_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT0_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT0_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT0_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT0_GPIO_OUT_BMSK                    0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT0_GPIO_OUT_SHFT                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT0_GPIO_IN_BMSK                     0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT0_GPIO_IN_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_ADDR                         (LPASS_TLMM_GPIO_REG_BASE      + 0x00001000)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_RMSK                             0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_GPIO_MISC_CFG_BMSK               0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_GPIO_MISC_CFG_SHFT                  0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_GPIO_HIHYS_EN_BMSK                0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_GPIO_HIHYS_EN_SHFT                  0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_GPIO_OE_BMSK                      0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_GPIO_OE_SHFT                        0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_GPIO_HDRIVE_BMSK                  0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_GPIO_HDRIVE_SHFT                    0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_GPIO_FUNC_SEL_BMSK                 0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_GPIO_FUNC_SEL_SHFT                  0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_GPIO_PULL_BMSK                      0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG1_GPIO_PULL_SHFT                      0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT1_ADDR                      (LPASS_TLMM_GPIO_REG_BASE      + 0x00001004)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT1_RMSK                             0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT1_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT1_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT1_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT1_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT1_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT1_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT1_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT1_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT1_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT1_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT1_GPIO_OUT_BMSK                    0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT1_GPIO_OUT_SHFT                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT1_GPIO_IN_BMSK                     0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT1_GPIO_IN_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_ADDR                         (LPASS_TLMM_GPIO_REG_BASE      + 0x00002000)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_RMSK                             0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_GPIO_MISC_CFG_BMSK               0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_GPIO_MISC_CFG_SHFT                  0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_GPIO_HIHYS_EN_BMSK                0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_GPIO_HIHYS_EN_SHFT                  0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_GPIO_OE_BMSK                      0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_GPIO_OE_SHFT                        0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_GPIO_HDRIVE_BMSK                  0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_GPIO_HDRIVE_SHFT                    0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_GPIO_FUNC_SEL_BMSK                 0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_GPIO_FUNC_SEL_SHFT                  0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_GPIO_PULL_BMSK                      0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG2_GPIO_PULL_SHFT                      0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT2_ADDR                      (LPASS_TLMM_GPIO_REG_BASE      + 0x00002004)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT2_RMSK                             0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT2_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT2_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT2_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT2_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT2_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT2_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT2_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT2_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT2_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT2_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT2_GPIO_OUT_BMSK                    0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT2_GPIO_OUT_SHFT                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT2_GPIO_IN_BMSK                     0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT2_GPIO_IN_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_ADDR                         (LPASS_TLMM_GPIO_REG_BASE      + 0x00002010)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_RMSK                             0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_GPIO_MISC_CFG_BMSK               0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_GPIO_MISC_CFG_SHFT                  0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_GPIO_HIHYS_EN_BMSK                0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_GPIO_HIHYS_EN_SHFT                  0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_GPIO_OE_BMSK                      0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_GPIO_OE_SHFT                        0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_GPIO_HDRIVE_BMSK                  0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_GPIO_HDRIVE_SHFT                    0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_GPIO_FUNC_SEL_BMSK                 0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_GPIO_FUNC_SEL_SHFT                  0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_GPIO_PULL_BMSK                      0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG3_GPIO_PULL_SHFT                      0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT3_ADDR                      (LPASS_TLMM_GPIO_REG_BASE      + 0x00002014)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT3_RMSK                             0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT3_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT3_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT3_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT3_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT3_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT3_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT3_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT3_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT3_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT3_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT3_GPIO_OUT_BMSK                    0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT3_GPIO_OUT_SHFT                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT3_GPIO_IN_BMSK                     0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT3_GPIO_IN_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_ADDR                         (LPASS_TLMM_GPIO_REG_BASE      + 0x00003000)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_RMSK                             0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_GPIO_MISC_CFG_BMSK               0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_GPIO_MISC_CFG_SHFT                  0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_GPIO_HIHYS_EN_BMSK                0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_GPIO_HIHYS_EN_SHFT                  0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_GPIO_OE_BMSK                      0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_GPIO_OE_SHFT                        0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_GPIO_HDRIVE_BMSK                  0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_GPIO_HDRIVE_SHFT                    0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_GPIO_FUNC_SEL_BMSK                 0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_GPIO_FUNC_SEL_SHFT                  0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_GPIO_PULL_BMSK                      0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG4_GPIO_PULL_SHFT                      0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT4_ADDR                      (LPASS_TLMM_GPIO_REG_BASE      + 0x00003004)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT4_RMSK                             0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT4_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT4_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT4_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT4_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT4_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT4_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT4_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT4_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT4_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT4_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT4_GPIO_OUT_BMSK                    0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT4_GPIO_OUT_SHFT                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT4_GPIO_IN_BMSK                     0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT4_GPIO_IN_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_ADDR                         (LPASS_TLMM_GPIO_REG_BASE      + 0x00003010)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_RMSK                             0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_GPIO_MISC_CFG_BMSK               0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_GPIO_MISC_CFG_SHFT                  0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_GPIO_HIHYS_EN_BMSK                0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_GPIO_HIHYS_EN_SHFT                  0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_GPIO_OE_BMSK                      0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_GPIO_OE_SHFT                        0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_GPIO_HDRIVE_BMSK                  0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_GPIO_HDRIVE_SHFT                    0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_GPIO_FUNC_SEL_BMSK                 0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_GPIO_FUNC_SEL_SHFT                  0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_GPIO_PULL_BMSK                      0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG5_GPIO_PULL_SHFT                      0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT5_ADDR                      (LPASS_TLMM_GPIO_REG_BASE      + 0x00003014)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT5_RMSK                             0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT5_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT5_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT5_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT5_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT5_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT5_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT5_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT5_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT5_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT5_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT5_GPIO_OUT_BMSK                    0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT5_GPIO_OUT_SHFT                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT5_GPIO_IN_BMSK                     0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT5_GPIO_IN_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_ADDR                         (LPASS_TLMM_GPIO_REG_BASE      + 0x00004000)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_RMSK                             0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_GPIO_MISC_CFG_BMSK               0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_GPIO_MISC_CFG_SHFT                  0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_GPIO_HIHYS_EN_BMSK                0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_GPIO_HIHYS_EN_SHFT                  0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_GPIO_OE_BMSK                      0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_GPIO_OE_SHFT                        0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_GPIO_HDRIVE_BMSK                  0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_GPIO_HDRIVE_SHFT                    0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_GPIO_FUNC_SEL_BMSK                 0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_GPIO_FUNC_SEL_SHFT                  0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_GPIO_PULL_BMSK                      0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG6_GPIO_PULL_SHFT                      0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT6_ADDR                      (LPASS_TLMM_GPIO_REG_BASE      + 0x00004004)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT6_RMSK                             0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT6_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT6_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT6_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT6_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT6_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT6_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT6_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT6_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT6_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT6_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT6_GPIO_OUT_BMSK                    0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT6_GPIO_OUT_SHFT                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT6_GPIO_IN_BMSK                     0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT6_GPIO_IN_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_ADDR                         (LPASS_TLMM_GPIO_REG_BASE      + 0x00004010)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_RMSK                             0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_GPIO_MISC_CFG_BMSK               0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_GPIO_MISC_CFG_SHFT                  0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_GPIO_HIHYS_EN_BMSK                0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_GPIO_HIHYS_EN_SHFT                  0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_GPIO_OE_BMSK                      0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_GPIO_OE_SHFT                        0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_GPIO_HDRIVE_BMSK                  0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_GPIO_HDRIVE_SHFT                    0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_GPIO_FUNC_SEL_BMSK                 0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_GPIO_FUNC_SEL_SHFT                  0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_GPIO_PULL_BMSK                      0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG7_GPIO_PULL_SHFT                      0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT7_ADDR                      (LPASS_TLMM_GPIO_REG_BASE      + 0x00004014)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT7_RMSK                             0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT7_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT7_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT7_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT7_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT7_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT7_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT7_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT7_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT7_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT7_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT7_GPIO_OUT_BMSK                    0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT7_GPIO_OUT_SHFT                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT7_GPIO_IN_BMSK                     0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT7_GPIO_IN_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_ADDR                         (LPASS_TLMM_GPIO_REG_BASE      + 0x00005000)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_RMSK                             0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_GPIO_MISC_CFG_BMSK               0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_GPIO_MISC_CFG_SHFT                  0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_GPIO_HIHYS_EN_BMSK                0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_GPIO_HIHYS_EN_SHFT                  0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_GPIO_OE_BMSK                      0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_GPIO_OE_SHFT                        0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_GPIO_HDRIVE_BMSK                  0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_GPIO_HDRIVE_SHFT                    0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_GPIO_FUNC_SEL_BMSK                 0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_GPIO_FUNC_SEL_SHFT                  0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_GPIO_PULL_BMSK                      0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG8_GPIO_PULL_SHFT                      0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT8_ADDR                      (LPASS_TLMM_GPIO_REG_BASE      + 0x00005004)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT8_RMSK                             0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT8_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT8_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT8_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT8_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT8_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT8_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT8_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT8_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT8_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT8_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT8_GPIO_OUT_BMSK                    0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT8_GPIO_OUT_SHFT                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT8_GPIO_IN_BMSK                     0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT8_GPIO_IN_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_ADDR                         (LPASS_TLMM_GPIO_REG_BASE      + 0x00005010)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_RMSK                             0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_GPIO_MISC_CFG_BMSK               0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_GPIO_MISC_CFG_SHFT                  0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_GPIO_HIHYS_EN_BMSK                0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_GPIO_HIHYS_EN_SHFT                  0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_GPIO_OE_BMSK                      0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_GPIO_OE_SHFT                        0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_GPIO_HDRIVE_BMSK                  0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_GPIO_HDRIVE_SHFT                    0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_GPIO_FUNC_SEL_BMSK                 0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_GPIO_FUNC_SEL_SHFT                  0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_GPIO_PULL_BMSK                      0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG9_GPIO_PULL_SHFT                      0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT9_ADDR                      (LPASS_TLMM_GPIO_REG_BASE      + 0x00005014)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT9_RMSK                             0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT9_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT9_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT9_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT9_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT9_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT9_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT9_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT9_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT9_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT9_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT9_GPIO_OUT_BMSK                    0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT9_GPIO_OUT_SHFT                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT9_GPIO_IN_BMSK                     0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT9_GPIO_IN_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x00005020)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG10_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT10_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x00005024)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT10_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT10_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT10_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT10_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT10_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT10_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT10_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT10_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT10_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT10_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT10_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT10_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT10_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT10_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT10_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x00005030)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG11_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT11_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x00005034)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT11_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT11_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT11_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT11_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT11_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT11_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT11_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT11_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT11_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT11_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT11_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT11_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT11_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT11_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT11_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x00005040)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG16_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT16_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x00005044)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT16_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT16_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT16_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT16_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT16_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT16_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT16_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT16_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT16_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT16_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT16_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT16_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT16_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT16_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT16_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x00005050)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG17_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT17_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x00005054)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT17_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT17_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT17_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT17_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT17_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT17_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT17_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT17_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT17_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT17_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT17_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT17_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT17_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT17_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT17_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x00006000)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG12_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT12_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x00006004)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT12_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT12_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT12_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT12_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT12_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT12_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT12_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT12_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT12_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT12_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT12_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT12_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT12_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT12_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT12_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x00006010)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG13_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT13_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x00006014)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT13_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT13_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT13_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT13_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT13_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT13_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT13_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT13_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT13_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT13_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT13_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT13_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT13_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT13_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT13_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x00007000)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG14_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT14_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x00007004)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT14_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT14_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT14_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT14_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT14_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT14_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT14_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT14_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT14_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT14_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT14_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT14_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT14_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT14_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT14_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x00007010)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG15_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT15_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x00007014)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT15_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT15_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT15_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT15_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT15_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT15_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT15_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT15_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT15_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT15_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT15_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT15_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT15_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT15_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT15_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x00008000)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG18_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT18_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x00008004)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT18_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT18_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT18_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT18_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT18_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT18_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT18_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT18_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT18_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT18_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT18_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT18_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT18_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT18_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT18_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x00008010)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG19_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT19_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x00008014)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT19_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT19_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT19_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT19_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT19_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT19_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT19_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT19_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT19_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT19_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT19_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT19_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT19_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT19_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT19_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x00008020)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG20_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT20_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x00008024)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT20_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT20_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT20_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT20_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT20_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT20_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT20_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT20_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT20_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT20_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT20_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT20_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT20_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT20_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT20_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x00008030)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG21_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT21_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x00008034)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT21_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT21_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT21_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT21_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT21_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT21_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT21_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT21_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT21_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT21_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT21_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT21_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT21_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT21_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT21_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x00008040)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG22_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT22_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x00008044)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT22_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT22_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT22_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT22_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT22_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT22_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT22_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT22_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT22_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT22_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT22_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT22_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT22_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT22_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT22_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x00008050)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG23_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT23_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x00008054)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT23_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT23_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT23_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT23_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT23_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT23_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT23_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT23_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT23_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT23_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT23_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT23_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT23_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT23_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT23_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x00008060)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG24_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT24_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x00008064)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT24_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT24_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT24_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT24_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT24_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT24_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT24_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT24_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT24_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT24_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT24_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT24_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT24_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT24_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT24_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x00008070)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG25_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT25_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x00008074)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT25_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT25_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT25_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT25_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT25_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT25_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT25_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT25_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT25_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT25_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT25_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT25_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT25_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT25_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT25_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x00009000)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG26_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT26_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x00009004)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT26_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT26_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT26_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT26_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT26_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT26_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT26_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT26_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT26_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT26_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT26_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT26_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT26_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT26_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT26_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x00009010)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG27_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT27_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x00009014)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT27_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT27_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT27_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT27_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT27_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT27_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT27_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT27_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT27_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT27_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT27_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT27_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT27_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT27_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT27_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x0000a000)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG28_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT28_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x0000a004)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT28_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT28_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT28_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT28_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT28_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT28_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT28_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT28_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT28_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT28_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT28_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT28_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT28_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT28_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT28_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x0000a010)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG29_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT29_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x0000a014)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT29_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT29_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT29_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT29_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT29_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT29_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT29_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT29_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT29_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT29_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT29_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT29_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT29_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT29_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT29_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x0000b000)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG30_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT30_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x0000b004)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT30_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT30_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT30_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT30_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT30_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT30_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT30_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT30_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT30_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT30_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT30_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT30_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT30_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT30_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT30_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_ADDR                        (LPASS_TLMM_GPIO_REG_BASE      + 0x0000b010)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_RMSK                            0xffff
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_GPIO_MISC_CFG_BMSK              0xf800
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_GPIO_MISC_CFG_SHFT                 0xb
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_GPIO_HIHYS_EN_BMSK               0x400
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_GPIO_HIHYS_EN_SHFT                 0xa
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_GPIO_OE_BMSK                     0x200
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_GPIO_OE_SHFT                       0x9
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_GPIO_HDRIVE_BMSK                 0x1c0
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_GPIO_HDRIVE_SHFT                   0x6
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_GPIO_FUNC_SEL_BMSK                0x3c
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_GPIO_FUNC_SEL_SHFT                 0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_GPIO_PULL_BMSK                     0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CFG31_GPIO_PULL_SHFT                     0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT31_ADDR                     (LPASS_TLMM_GPIO_REG_BASE      + 0x0000b014)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT31_RMSK                            0x3
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT31_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT31_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT31_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT31_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT31_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT31_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT31_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT31_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT31_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT31_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT31_GPIO_OUT_BMSK                   0x2
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT31_GPIO_OUT_SHFT                   0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT31_GPIO_IN_BMSK                    0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_IN_OUT31_GPIO_IN_SHFT                    0x0

#define HWIO_LPASS_TLMM_GPIO_ISLAND_CODEC_RST_ADDR                    (LPASS_TLMM_GPIO_REG_BASE      + 0x0000f000)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CODEC_RST_RMSK                           0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CODEC_RST_IN          \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CODEC_RST_ADDR, HWIO_LPASS_TLMM_GPIO_ISLAND_CODEC_RST_RMSK)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CODEC_RST_INM(m)      \
        in_dword_masked(HWIO_LPASS_TLMM_GPIO_ISLAND_CODEC_RST_ADDR, m)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CODEC_RST_OUT(v)      \
        out_dword(HWIO_LPASS_TLMM_GPIO_ISLAND_CODEC_RST_ADDR,v)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CODEC_RST_OUTM(m,v) \
        out_dword_masked_ns(HWIO_LPASS_TLMM_GPIO_ISLAND_CODEC_RST_ADDR,m,v,HWIO_LPASS_TLMM_GPIO_ISLAND_CODEC_RST_IN)
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CODEC_RST_CODEC_RST_BMSK                 0x1
#define HWIO_LPASS_TLMM_GPIO_ISLAND_CODEC_RST_CODEC_RST_SHFT                 0x0


#endif /* __UHALTLMMHWIO_H__ */
