#===============================================================================
#
# teetest Build Script
#
# GENERAL DESCRIPTION
#    build script
#
# Copyright (c) 2015 Qualcomm Technologies, Inc.
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.
#
#-------------------------------------------------------------------------------
#
#  $Header: //components/rel/core.tz/1.0.7.1/securemsm/trustzone/qsapps/teetest/teetest/src/SConscript#1 $
#  $DateTime: 2020/01/14 12:35:09 $
#  $Author: pwbldsvc $
#  $Change: 22186835 $
#                      EDIT HISTORY FOR FILE
#
#  This section contains comments describing changes made to the module.
#  Notice that changes are listed in reverse chronological order.
#
#===============================================================================
Import('env')

includes = [
   "${CHIPSET}",
]

#----------------------------------------------------------------------------
# Disable the optimizer for the MINK PVC integration. This code is too darn
# hard to follow otherwise. This can be disabled from commandline as well,
# but that is a good idea only if you are building teetest; not when you
# are compiling everything with tzbsptest
#----------------------------------------------------------------------------
env.Replace(ARMCC_OPT = "")

env.Append(CCFLAGS = " -mfpu=none ")

#----------------------------------------------------------------------------
# App core Objects
#----------------------------------------------------------------------------
sources = [
   'teetest_cache.s',
   'teetest_entry.s',
   'teetest_mmu.s',
   'teetest_mmu_func.c',
   'teetest_smc.s',
   'teetest.c',
   'teetest_secdisp.c',
   'teetest_hal_qgic.c',
   'teetest_i2c.c',
   'teetest_crypto.c',
   'CEnv.c',
   'CGuestVM.c',
]

#-------------------------------------------------------------------------------
# Add metadata to image
#-------------------------------------------------------------------------------
md = {
}

teetest_units = env.SecureAppBuilder(
  sources = sources,
  includes = includes,
  metadata = md,
  image = 'teetest',
)

for image in env['IMAGE_ALIASES']:
  op = env.Alias(image, teetest_units)
